USE energov381407prod_ThousandOaksCA

SELECT 
	  PT.NAME [Permit Type Name]
	, PT.PERMITPREFIX [Naming Scheme]
	, PS1.NAME [Default Status]
	, PS2.NAME [Default Online Status]
	, PT.DAYSUNTILEXPIRE [Days Until Expiration] 
	, PT.DAYSUNTILEXPIREFROMLASTINSPECT [Days Until Expire From Last Inspection] 

FROM PMPERMITTYPE PT 
LEFT JOIN PMPERMITSTATUS PS1 ON PS1.PMPERMITSTATUSID = PT.DEFAULTPMPERMITSTATUSID
LEFT JOIN PMPERMITSTATUS PS2 ON PS2.PMPERMITSTATUSID = PT.DEFAULTWEBPMPERMITSTATUSID
WHERE PT.NAME = 'Combination Permit (BMEP)'