SELECT DISTINCT 
	    ST.TYPENAME [Submittal Type Name]
	  , IRT.NAME [Item Review Name]
	  , D.NAME [Department Name]
	  --Is this correct? Does not match results in Excel
	  , IA.NAME [Assignment Method]
	  , T.NAME [Team or User Names]
	  , IRT.DAYSUNTILDUE [Days to Review]
	  , IRT.RESUMITALDAYSUNTILDUE [Resubmittal Days to Review]
	  , STIRT.PRIORITY [Review Priority]
	  --Not sure where this is pulled from
	  , 'Visible by Default'
	  --Is this the right notes field?
	  , SN.TEXT [Notes] 
FROM PLPLAN PL
LEFT JOIN PLSUBMITTAL S ON S.PLPLANID = PL.PLPLANID
--INNER JOIN creates 0 rows, the table is for the permit module
LEFT JOIN PMPERMIT PM ON PM.PMPERMITID = S.PMPERMITID
LEFT JOIN PLSUBMITTALTYPE ST ON ST.PLSUBMITTALTYPEID = S.PLSUBMITTALTYPEID
LEFT JOIN PLITEMREVIEW IR ON IR.PLPLANID = PL.PLPLANID
LEFT JOIN PLITEMREVIEWTYPE IRT ON IRT.PLITEMREVIEWTYPEID = IR.PLITEMREVIEWTYPEID
LEFT JOIN DEPARTMENT D ON D.DEPARTMENTID = IRT.DEPARTMENTID
LEFT JOIN IMINSPECTIONTYPE IT ON IT.DEPARTMENTID = D.DEPARTMENTID
LEFT JOIN IMINSPECTIONGISASSIGNMENT IA ON IA.IMINSPECTIONGISASSIGNMENTID = IT.IMINSPECTIONGISASSIGNMENTID 
LEFT JOIN TEAM T ON T.TEAMID = IRT.TEAMASSIGNEDTOID 
LEFT JOIN PLSUBMITTALTYPEITEMREVIEWTYPEX STIRT ON STIRT.PLSUBMITTALTYPEID = S.PLSUBMITTALTYPEID
LEFT JOIN PLSUBMITTALNOTE SN ON SN.PLSUBMITTALID = S.PLSUBMITTALID
