SELECT 
	CASE 
		WHEN WFAS.PMPERMITWFACTIONSTEPID IS NULL THEN 'Step'
		ELSE 'Action'
	END
FROM PMPERMIT P
LEFT JOIN PMPERMITWFSTEP WFS ON WFS.PMPERMITID = P.PMPERMITID 
LEFT JOIN PMPERMITWFACTIONSTEP WFAS ON WFAS.PMPERMITWFSTEPID = WFS.PMPERMITWFSTEPID