USE [energov5698prod_SunnyvaleCA]
--GO

--SET ANSI_NULLS ON 
--GO

--SET QUOTED_IDENTIFIER ON 
--GO

--CREATE PROCEDURE [dbo].[rpt_CoS_PM_Engineering Project Information Sheet]
--@PMPERMITID AS CHAR(36)

--AS 

--BEGIN

DECLARE @PMPERMITID AS CHAR(36) = '0001285F-B4C1-4291-956B-A3F1C93D6C07'

;WITH CONTACTS AS (
SELECT 
	 PMC.PMPERMITID
	,GE.FIRSTNAME [FirstName]
	,GE.LASTNAME [LastName]
	,RTRIM(LTRIM(COALESCE(MA.POBOX, '') + ' ')
	+ LTRIM(COALESCE(MA.ADDRESSLINE1, '') + ' ')
	+ LTRIM(COALESCE(MA.PREDIRECTION, '') + ' ')
	+ LTRIM(COALESCE(MA.ADDRESSLINE2, '') + ' ')
	+ LTRIM(COALESCE(MA.STREETTYPE, '') + ' ')
	+ LTRIM(COALESCE(MA.POSTDIRECTION, '') + ' ')
	+ LTRIM(COALESCE(MA.UNITORSUITE, '') + ' ')
	) [AddressLine1]
	,(CASE WHEN RTRIM(LTRIM(COALESCE(MA.CITY, ''))) = '' THEN '' ELSE RTRIM(LTRIM(COALESCE(MA.CITY, ''))) + ', ' END
	+ LTRIM(COALESCE(MA.STATE, '') + ' ')
	+ REPLACE((CASE WHEN LEN(REPLACE(COALESCE(MA.POSTALCODE, ''), ' ', '')) > 5 
			    THEN LEFT(REPLACE(COALESCE(MA.POSTALCODE, ''), ' ', ''), 5) + '-' + RIGHT(REPLACE(COALESCE(MA.POSTALCODE, ''), ' ', ''), ABS(LEN(REPLACE(COALESCE(MA.POSTALCODE, ''), ' ', '')) -5)) 
				ELSE COALESCE(MA.POSTALCODE, '') END), '--', '-')
	) [AddressLine2] 
	,COALESCE(GE.BUSINESSPHONE, GE.MOBILEPHONE, GE.HOMEPHONE, GE.OTHERPHONE) [PhoneNumber] 
	,GE.GLOBALENTITYID [GlobalEntityID]
	,GE.GLOBALENTITYNAME [CompanyName]
	,LMCT.NAME [ContactType]
	,PMC.ISBILLING [IsBilling]
	,ROW_NUMBER() OVER (PARTITION BY PMC.PMPERMITID, CASE WHEN LMCT.NAME LIKE '%Owner%' THEN 1
														  WHEN LMCT.NAME LIKE '%Contractor%' THEN 2 
														  ELSE 3 
														  END ORDER BY PMC.ISBILLING DESC, GE.GLOBALENTITYID) [ROWNBR]
FROM PMPERMITCONTACT PMC
INNER JOIN PMPERMIT P ON P.PMPERMITID = PMC.PMPERMITID
INNER JOIN GLOBALENTITY GE ON GE.GLOBALENTITYID = PMC.GLOBALENTITYID 
INNER JOIN LANDMANAGEMENTCONTACTTYPE LMCT ON LMCT.LANDMANAGEMENTCONTACTTYPEID = PMC.LANDMANAGEMENTCONTACTTYPEID
LEFT JOIN PMPERMITADDRESS PA ON PA.PMPERMITID = P.PMPERMITID
LEFT JOIN MAILINGADDRESS MA ON PA.MAILINGADDRESSID = MA.MAILINGADDRESSID
WHERE P.PMPERMITID = @PMPERMITID
)

,FEES AS (
SELECT
	 P.PMPERMITID
	,CF.FEENAME [FeeName]
	,CF.COMPUTEDAMOUNT [ComputedAmount]
	,CF.CREATEDON [Created Date] 
	,TP.PAYMENTDATE [PaymentDate]
	,CF.AMOUNTPAIDTODATE [AmountPaidToDate]
	,I.INVOICENUMBER [InvoiceNumber]
FROM PMPERMITFEE PF
LEFT JOIN PMPERMIT P ON P.PMPERMITID = PF.PMPERMITID
LEFT JOIN CACOMPUTEDFEE CF ON CF.CACOMPUTEDFEEID = PF.CACOMPUTEDFEEID
	AND CF.CASTATUSID NOT IN (5,10)
LEFT JOIN CATRANSACTIONFEE TFEE ON TFEE.CACOMPUTEDFEEID = CF.CACOMPUTEDFEEID 
LEFT JOIN CATRANSACTION T ON T.CATRANSACTIONID = TFEE.CATRANSACTIONID
	AND T.CATRANSACTIONTYPEID = 1
LEFT JOIN CATRANSACTIONPAYMENT TP ON TP.CATRANSACTIONID = T.CATRANSACTIONID
LEFT JOIN CATRANSACTIONINVOICE TAI ON TAI.CATRANSACTIONID = T.CATRANSACTIONID
LEFT JOIN CAINVOICE I ON I.CAINVOICEID = TAI.CAINVOICEID
WHERE P.PMPERMITID = @PMPERMITID
)

, WF AS (
SELECT
	 P.PMPERMITID
	,WFA.VERSIONNUMBER [VersionNumber]
	,ROW_NUMBER() OVER (PARTITION BY P.PMPERMITID ORDER BY WFA.VERSIONNUMBER) [VersionROWNumber]
FROM PMPERMITWFSTEP WFS
LEFT JOIN PMPERMITWFACTIONSTEP WFA ON WFA.PMPERMITWFSTEPID = WFS.PMPERMITWFSTEPID
LEFT JOIN PMPERMIT P ON P.PMPERMITID = WFS.PMPERMITID
WHERE P.PMPERMITID = @PMPERMITID
)

SELECT 
 P.PMPERMITID
,P.PERMITNUMBER AS PERMITNUMBER
,P.DESCRIPTION AS DESCRIPTION 
,P.APPLYDATE AS APPLYDATE
,P.ISSUEDATE AS ISSUEDATE
,PS.NAME AS PERMITSTATUS
,RTRIM(LTRIM(COALESCE(MA.POBOX, '') + ' ')
	+ LTRIM(COALESCE(MA.ADDRESSLINE1, '') + ' ')
	+ LTRIM(COALESCE(MA.PREDIRECTION, '') + ' ')
	+ LTRIM(COALESCE(MA.ADDRESSLINE2, '') + ' ')
	+ LTRIM(COALESCE(MA.STREETTYPE, '') + ' ')
	+ LTRIM(COALESCE(MA.POSTDIRECTION, '') + ' ')
	+ LTRIM(COALESCE(MA.UNITORSUITE, '') + ' ')
) AS ADDRESSLINE1
,(CASE WHEN RTRIM(LTRIM(COALESCE(MA.CITY, ''))) = '' THEN '' ELSE RTRIM(LTRIM(COALESCE(MA.CITY, ''))) + ', ' END
+ LTRIM(COALESCE(MA.STATE, '') + ' ')
+ REPLACE((CASE WHEN LEN(REPLACE(COALESCE(MA.POSTALCODE, ''), ' ', '')) > 5 
			    THEN LEFT(REPLACE(COALESCE(MA.POSTALCODE, ''), ' ', ''), 5) + '-' + RIGHT(REPLACE(COALESCE(MA.POSTALCODE, ''), ' ', ''), ABS(LEN(REPLACE(COALESCE(MA.POSTALCODE, ''), ' ', '')) -5)) 
				ELSE COALESCE(MA.POSTALCODE, '') END), '--', '-')
) AS ADDRESSLINE2 
,PCEL.PARCELNUMBER AS PARCELNUMBER 
,MAX(WF.VERSIONNUMBER) OVER (PARTITION BY P.PMPERMITID) AS VERSIONNUMBER
,STUFF((
		SELECT ', ' + [Pick].[SVALUE]
		FROM CUSTOMSAVERPERMITMANAGEMENTMS MS 
		JOIN CUSTOMFIELDPICKLISTITEM Pick ON Pick.GCUSTOMFIELDPICKLISTITEM = MS.CUSTOMFIELDPICKLISTITEMID 
		WHERE 
			MS.ID = @PMPERMITID 
			AND
			MS.CUSTOMFIELDID IN (SELECT C.GCUSTOMFIELD		
								 FROM CUSTOMFIELD C 
								 WHERE C.SFIELDNAME LIKE 'PCK_PWType')
		ORDER BY Pick.SVALUE 
		FOR XML PATH ('')
		, root('MyString'), type)
		. value('/MyString[1]', 'varchar(max)')
		, 1, 2, ''
) AS PWTYPE
,PI_USE.SVALUE AS [USE]
,PI_ENG.SVALUE AS ENGINEER 
,CS.MEMO_LocationDescription AS LOCATIONDESCRIPTION
,CS.MEMO_OtherDescription AS OTHERDESC
,CS.TXT_Development AS DEVELOPMENT
,CS.TXT_TractMapNum AS FINALMAPNUMBER 
,CS.TXT_ParcelMapNum AS PARCELMAPNUMBER
,CS.TXT_PWPlanNum AS PWPLANNUMBER
,CS.TXT_AcceptDate AS ACCEPTDATE
,(SELECT IMAGE FROM RPTIMAGELIB WHERE IMAGENAME LIKE 'Sunnyvale_BW_Vertical_Logo') AS SunnyvaleLogo
,F.FeeName
,F.ComputedAmount
,F.AmountPaidToDate
,F.[Created Date]
,F.PaymentDate
,F.InvoiceNumber
,CON.ContactType AS CONTACTTYPE
,STUFF((
	SELECT ', ' + CON.FirstName + ' ' + CON.LastName
	FROM CONTACTS CON
	WHERE CON.PMPERMITID = P.PMPERMITID
	AND CON.ContactType = 'Owner'
	FOR XML PATH (''), root('MyString'), type).value('/MyString[1]', 'varchar(max)'), 1, 2, ''
) AS OWNERS
,CON.FIRSTNAME + ' ' + CON.LASTNAME AS CONTACTNAME
,CON.AddressLine1 AS ADDRESSLINE1
,CON.AddressLine2 AS ADDRESSLINE2
,CON.PhoneNumber AS PHONENUMBER 
FROM PMPERMIT P
LEFT JOIN PMPERMITSTATUS PS ON PS.PMPERMITSTATUSID = P.PMPERMITSTATUSID
LEFT JOIN PMPERMITADDRESS PA ON PA.PMPERMITID = P.PMPERMITID
LEFT JOIN MAILINGADDRESS MA ON MA.MAILINGADDRESSID = PA.MAILINGADDRESSID
LEFT JOIN PMPERMITPARCEL PPAR ON PPAR.PMPERMITID = P.PMPERMITID
LEFT JOIN PARCEL PCEL ON PCEL.PARCELID = PPAR.PARCELID
LEFT JOIN CUSTOMSAVERPERMITMANAGEMENT CS ON CS.ID = P.PMPERMITID
LEFT JOIN CUSTOMFIELDPICKLISTITEM PI_USE ON PI_USE.GCUSTOMFIELDPICKLISTITEM = CS.PCK_PWUse
LEFT JOIN CUSTOMFIELDPICKLISTITEM PI_ENG ON PI_ENG.GCUSTOMFIELDPICKLISTITEM = CS.PCK_Engineer
LEFT JOIN CONTACTS CON ON CON.PMPERMITID = P.PMPERMITID
LEFT JOIN FEES F ON F.PMPERMITID = P.PMPERMITID
LEFT JOIN WF ON WF.PMPERMITID = P.PMPERMITID
WHERE P.PMPERMITID = @PMPERMITID

--END 
--GO



