USE [EnerGov_Tucson_Prod]
--GO

--/****** Object:  StoredProcedure [dbo].[rpt_CoT_CM_NoticeofViolation_iG]    Script Date: 8/13/2025 2:19:02 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO


--CREATE PROCEDURE [dbo].[rpt_CoT_CM_NoticeofViolation_iG]
--	@CMCODECASEID AS CHAR(36)
--AS

--BEGIN
--EXEC rpt_CoT_CM_NoticeofViolation '002b7f25-75bc-4e7f-9aa9-2af2f92b90e2', 'Owner'
--DECLARE @CMCODECASEID AS CHAR(36) = '7e451606-e4e8-491e-97f3-e0d1f5826ae2';
--DECLARE @CMCODECASEID AS CHAR(36) = '002b7f25-75bc-4e7f-9aa9-2af2f92b90e2';
--DECLARE @CONTACTTYPE AS NVARCHAR(50) = 'Tenant';

/*BUILD VIOLATION LIST*/
DROP TABLE IF EXISTS #VIO;
DROP TABLE IF EXISTS #CONTACT;
DROP TABLE IF EXISTS #CONTACTADDRESS;
DROP TABLE IF EXISTS #MADDRESS;
		  


SELECT CWFS.CMCODECASEID,CV.CITATIONISSUEDATE, CV.COMPLIANCEDATE, CV.CORRECTIVEACTION,
	C.CODENUMBER, C.DESCRIPTION, 
	CR.CODETEXT REVISIONCODETEXT
INTO #VIO
FROM CMCODEWFSTEP CWFS
INNER JOIN CMVIOLATION CV ON CWFS.CMCODEWFSTEPID = CV.CMCODEWFSTEPID
INNER JOIN CMVIOLATIONSTATUS VS ON CV.CMVIOLATIONSTATUSID = VS.CMVIOLATIONSTATUSID AND VS.SUCCESSFLAG <> 1
INNER JOIN CMCODE C ON CV.CMCODEID = C.CMCODEID 
INNER JOIN CMCODEREVISION CR ON C.CMCODEID = CR.CMCODEID AND CR.CURRENTREVISION = 1
--WHERE CWFS.CMCODECASEID = @CMCODECASEID

/*BUILD CONTACT LIST*/
SELECT CCC.CMCODECASEID, GE.FIRSTNAME, GE.LASTNAME, GE.GLOBALENTITYID, CCCT.NAME CONTACTTYPE, GE.GLOBALENTITYNAME COMPANYNAME, 
	CCC.ISBILLING, GE.GLOBALENTITYNAME, GE.[IMAGE], GE.ISCOMPANY, GE.ISCONTACT, GE.MIDDLENAME,
	CASE	WHEN LEN(LTRIM(GE.BUSINESSPHONE)) > 0 THEN GE.BUSINESSPHONE 
		WHEN LEN(LTRIM(GE.MOBILEPHONE)) > 0 THEN GE.MOBILEPHONE 
		WHEN LEN(LTRIM(GE.HOMEPHONE)) > 0 THEN GE.HOMEPHONE 
		WHEN LEN(LTRIM(GE.OTHERPHONE)) > 0 THEN GE.OTHERPHONE 
		ELSE '' END AS PHONE
	, ROW_NUMBER() OVER (PARTITION BY CCC.CMCODECASEID, CCCT.[NAME] ORDER BY CCC.ISBILLING DESC) ROWNBR
INTO #CONTACT
FROM CMCODECASECONTACT CCC
INNER JOIN GLOBALENTITY GE ON CCC.GLOBALENTITYID = GE.GLOBALENTITYID
INNER JOIN CMCODECASECONTACTTYPE CCCT ON CCC.CMCODECASECONTACTTYPEID = CCCT.CMCODECASECONTACTTYPEID
--WHERE CCC.CMCODECASEID = @CMCODECASEID

/*BUILD LIST OF ADDRESSES FOR CONTACTS*/
SELECT GEMA.GLOBALENTITYID, MA.ADDRESSTYPE, RTRIM(MA.ADDRESSLINE1 + ' ' +	LTRIM(MA.PREDIRECTION + ' ') + LTRIM(MA.ADDRESSLINE2 + ' ') + 
	LTRIM(MA.STREETTYPE + ' ') + LTRIM(MA.POSTDIRECTION + ' ') + LTRIM(MA.UNITORSUITE + ' ')  + LTRIM(MA.ADDRESSLINE3)) ADDRESS_LINE1,
	RTRIM(CASE WHEN RTRIM(LTRIM(MA.CITY)) = '' THEN '' ELSE LTRIM(MA.CITY + ', ' ) END + LTRIM(MA.STATE + ' ') + 
	(CASE WHEN LEN(REPLACE(ISNULL(MA.POSTALCODE,''),'-','')) > 5 
		THEN SUBSTRING(REPLACE(ISNULL(MA.POSTALCODE,''),'-',''),1,5) + '-' + SUBSTRING(REPLACE(ISNULL(MA.POSTALCODE,''),'-',''),6,4)
		ELSE REPLACE(ISNULL(MA.POSTALCODE,''),'-','') END)) ADDRESS_LINE2,
	ROW_NUMBER() OVER (PARTITION BY GEMA.GLOBALENTITYID ORDER BY CASE WHEN MA.ADDRESSTYPE LIKE 'Mailing%' THEN 1 WHEN MA.ADDRESSTYPE LIKE 'Billing%' THEN 2 WHEN MA.ADDRESSTYPE LIKE 'Location%' THEN 3 ELSE 4 END, MA.MAILINGADDRESSID) AS ROWNBR
INTO #CONTACTADDRESS
FROM GLOBALENTITYMAILINGADDRESS GEMA 
INNER JOIN MAILINGADDRESS MA ON GEMA.MAILINGADDRESSID = MA.MAILINGADDRESSID

/*MAIN CASE ADDRESS*/
SELECT CCA.MAIN, CCA.CMCODECASEID, MA.ADDRESSTYPE, RTRIM(MA.ADDRESSLINE1 + ' ' +	LTRIM(MA.PREDIRECTION + ' ') + LTRIM(MA.ADDRESSLINE2 + ' ') + 
	LTRIM(MA.STREETTYPE + ' ') + LTRIM(MA.POSTDIRECTION + ' ') + LTRIM(MA.UNITORSUITE + ' ')  + LTRIM(MA.ADDRESSLINE3)) ADDRESS_LINE1,
	RTRIM(CASE WHEN RTRIM(LTRIM(MA.CITY)) = '' THEN '' ELSE LTRIM(MA.CITY + ', ' ) END + LTRIM(MA.STATE + ' ') + 
	(CASE WHEN LEN(REPLACE(ISNULL(MA.POSTALCODE,''),'-','')) > 5 
		THEN SUBSTRING(REPLACE(ISNULL(MA.POSTALCODE,''),'-',''),1,5) + '-' + SUBSTRING(REPLACE(ISNULL(MA.POSTALCODE,''),'-',''),6,4)
		ELSE REPLACE(ISNULL(MA.POSTALCODE,''),'-','') END)) ADDRESS_LINE2
INTO #MADDRESS
FROM CMCODECASEADDRESS CCA
INNER JOIN MAILINGADDRESS MA ON CCA.MAILINGADDRESSID = MA.MAILINGADDRESSID
WHERE 
--CCA.CMCODECASEID = @CMCODECASEID AND 
CCA.MAIN = 1

CREATE INDEX TEMP1 ON #VIO (CMCODECASEID);
CREATE INDEX TEMP1 ON #CONTACT (CMCODECASEID);
CREATE INDEX TEMP1 ON #CONTACTADDRESS (GLOBALENTITYID);
CREATE INDEX TEMP2 ON #CONTACTADDRESS (ROWNBR);
CREATE INDEX TEMP1 ON #MADDRESS (CMCODECASEID);

/*BEGIN MAIN QUERY*/
WITH CODEINSPECTIONS AS (
SELECT INSP.IMINSPECTIONID, INSP.INSPECTIONNUMBER, INSP.LINKID, INSP.LINKNUMBER, U.FNAME, U.LNAME, U.[CREDENTIALS], U.PHONE
	, INSP.ACTUALSTARTDATE, ISTAT.[STATUSNAME]	
	, ROW_NUMBER () OVER (ORDER BY CASE WHEN ISTAT.[STATUSNAME] LIKE 'In Violation' THEN 1 ELSE 10 END, INSP.ACTUALSTARTDATE DESC) ROWNUMBER
	, CWFAS.*
FROM IMINSPECTION INSP
INNER JOIN IMINSPECTIONSTATUS ISTAT ON INSP.IMINSPECTIONSTATUSID = ISTAT.IMINSPECTIONSTATUSID
LEFT JOIN IMINSPECTORREF IREF ON INSP.IMINSPECTIONID = IREF.INSPECTIONID
LEFT JOIN USERS U ON IREF.USERID = U.SUSERGUID
LEFT JOIN IMINSPECTIONACTREF REF ON INSP.IMINSPECTIONID = REF.IMINSPECTIONID
LEFT JOIN CMCODEWFACTIONSTEP CWFAS ON REF.OBJECTID = CWFAS.CMCODEWFACTIONSTEPID
LEFT JOIN IMINSPECTIONTYPE IT ON CWFAS.IMINSPECTIONTYPEID = IT.IMINSPECTIONTYPEID
--WHERE INSP.LINKID = @CMCODECASEID
)
SELECT CM.CMCODECASEID, CM.CASENUMBER, CM.OPENEDDATE,
	CT.NAME CASETYPE,
	P.PARCELNUMBER, P.NAME1 PAROWNERNAME, P.ADDRESSLINE1 PAROWN_ADDRESSLINE1
	, (CASE WHEN RTRIM(LTRIM(COALESCE(P.CITY,''))) = '' 
			THEN '' 
			ELSE RTRIM(LTRIM(COALESCE(P.CITY,''))) + ', ' END)
			+ (LTRIM(COALESCE(P.[STATE],'') + ' ') 
			+ REPLACE((CASE WHEN LEN(REPLACE(COALESCE(P.POSTALCODE,''),' ','')) > 5 
			THEN LEFT(REPLACE(COALESCE(P.POSTALCODE,''),' ',''),5) + '-' + RIGHT(REPLACE(COALESCE(P.POSTALCODE,''),' ',''),ABS(LEN(REPLACE(COALESCE(P.POSTALCODE,''),' ',''))-5)) 
			ELSE COALESCE(P.POSTALCODE,'') END),'--','-')
	 ) PAROWN_ADDRESSLINE2
	, CI.ACTUALSTARTDATE INSPECTIONDATE, CS.TXT_Location,
	VIO.CITATIONISSUEDATE, VIO.COMPLIANCEDATE, VIO.CODENUMBER, VIO.DESCRIPTION, VIO.REVISIONCODETEXT, VIO.CORRECTIVEACTION,
	CASE WHEN CON.ISCONTACT = 1 THEN CON.FIRSTNAME + ' ' + CON.LASTNAME ELSE CON.GLOBALENTITYNAME END CONTACTNAME, CON.CONTACTTYPE,
	CONADD.ADDRESS_LINE1, CONADD.ADDRESS_LINE2, CON.GLOBALENTITYID,
	MA.ADDRESS_LINE1 MADDRESS_LINE1, MA.ADDRESS_LINE2 MADDRESS_LINE2,
	U.FNAME + ' ' + U.LNAME ASSIGNEDTO, U.TITLE, U.PHONE [Assigned To Phone]
	, CI.FNAME + ' ' + CI.LNAME INSPECTORNAME--, CI.[CREDENTIALS]
	, CI.PHONE [InspectorPhone]
	, PI_RESPONSIBLEPARTY.SVALUE RESPONSIBLEPARTY
	, CS.ComplianceDeadline COMPLIANCEDEADLINE
	, CS.MON_CostAbatement COSTOFABATEMENT
	, CASE WHEN (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = CI.FNAME + '.' + CI.LNAME) IS NULL
		THEN (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = U.FNAME + '.' + U.LNAME) 
		ELSE (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = CI.FNAME + '.' + CI.LNAME) END [CREDENTIALS]
	, CASE WHEN (SELECT [IMAGE] FROM RPTIMAGELIB WHERE IMAGENAME = CI.FNAME + '.' + CI.LNAME) IS NULL
		THEN (SELECT [IMAGE] FROM RPTIMAGELIB WHERE IMAGENAME = U.FNAME + '.' + U.LNAME)
		ELSE (SELECT R.[IMAGE] FROM RPTIMAGELIB R WHERE R.IMAGENAME = CI.FNAME + '.' + CI.LNAME) END INSPECTORSIGNATURE
	, CASE WHEN CT.[NAME] LIKE 'Code Enforcement Case' THEN (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'CEIntro_NOV')
		WHEN CT.[NAME] LIKE 'Fire Code Case' THEN (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'TFDIntro_NOV')
		WHEN CT.[NAME] LIKE 'Right-of-Way Notice of Violation' THEN (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'DTMIntro_NOV')
		WHEN CT.[NAME] LIKE 'Water Waste Violation' THEN (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'WWIntro_NOV')
		END NOVIntroText
	, CASE WHEN CT.[NAME] LIKE 'Code Enforcement Case' THEN (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'CEHeader')
		WHEN CT.[NAME] LIKE 'Fire Code Case' THEN (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'TFDHeader')
		WHEN CT.[NAME] LIKE 'Right-of-Way Notice of Violation' THEN (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'DTMHeader')
		END NOVHeader
	, CASE WHEN CT.[NAME] LIKE 'Code Enforcement Case' THEN (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'CELegalese_NOV')
		WHEN CT.[NAME] LIKE 'Fire Code Case' THEN (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'TFDLegalese_NOV')
		WHEN CT.[NAME] LIKE 'Right-of-Way Notice of Violation' THEN (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'DTMLegalese_NOV')
		WHEN CT.[NAME] LIKE 'Water Waste Violation' THEN (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'WWLegalese_NOV')
		END NOVLegaleseText
	, CASE WHEN CT.[NAME] LIKE 'Code Enforcement Case' THEN (SELECT R.[IMAGE] FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'TucsonLogo')
		WHEN CT.[NAME] LIKE 'Fire Code Case' THEN (SELECT R.[IMAGE] FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'TFDLogo')
		WHEN CT.[NAME] LIKE 'Right-of-Way Notice of Violation' THEN (SELECT R.[IMAGE] FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'TucsonLogo')
		WHEN CT.[NAME] LIKE 'Water Waste Violation' THEN (SELECT R.[IMAGE] FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'TucsonWaterLogo')
		END Logo
FROM CMCODECASE CM
INNER JOIN CMCASETYPE CT ON CM.CMCASETYPEID = CT.CMCASETYPEID
LEFT JOIN CMCODECASEPARCEL CP ON CM.CMCODECASEID = CP.CMCODECASEID AND CP.[PRIMARY] = 1
LEFT JOIN PARCEL P ON CP.PARCELID = P.PARCELID 
LEFT JOIN #VIO VIO ON CM.CMCODECASEID = VIO.CMCODECASEID
LEFT JOIN #CONTACT CON ON CM.CMCODECASEID = CON.CMCODECASEID AND CON.ROWNBR = 1 AND CON.CONTACTTYPE IN (SELECT  PI_RESPONSIBLEPARTY.SVALUE FROM CUSTOMSAVERCODEMANAGEMENT CS1 
																					LEFT JOIN CUSTOMFIELDPICKLISTITEM PI_RESPONSIBLEPARTY 
																					ON CS1.PCK_ResponsibleParty = PI_RESPONSIBLEPARTY.GCUSTOMFIELDPICKLISTITEM  
																					--WHERE CS1.ID = @CMCODECASEID
																					)
LEFT JOIN #CONTACTADDRESS CONADD ON CON.GLOBALENTITYID = CONADD.GLOBALENTITYID AND CONADD.ROWNBR = 1
LEFT JOIN #MADDRESS MA ON CM.CMCODECASEID = MA.CMCODECASEID
LEFT JOIN USERS U ON CM.ASSIGNEDTO = U.SUSERGUID
LEFT JOIN CODEINSPECTIONS CI ON CM.CMCODECASEID = CI.LINKID AND CI.ROWNUMBER = 1
LEFT JOIN CUSTOMSAVERCODEMANAGEMENT CS ON CM.CMCODECASEID = CS.ID
LEFT JOIN CUSTOMFIELDPICKLISTITEM PI_RESPONSIBLEPARTY ON CS.PCK_ResponsibleParty = PI_RESPONSIBLEPARTY.GCUSTOMFIELDPICKLISTITEM
--WHERE CM.CMCODECASEID = @CMCODECASEID
--WHERE CM.CASENUMBER LIKE '%CE-VIO%'



--END
--GO


