USE [EnerGov_Tucson_Prod]
--GO

--/****** Object:  StoredProcedure [dbo].[rpt_CoT_PM_FireConstructionPermit]    Script Date: 8/13/2025 11:45:07 AM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO


--CREATE PROCEDURE [dbo].[rpt_CoT_PM_FireConstructionPermit]
--	@PMPERMITID AS CHAR(36)
--AS

--BEGIN
----DECLARE @PMPERMITID AS CHAR(36) = '04332bcc-71a5-4533-b80f-dc3261284b14';
;WITH
CONTACTS AS (
	SELECT PC.PMPERMITID, PC.GLOBALENTITYID
		, LMCT.[NAME] CONTACTTYPE
		, GE.FIRSTNAME + ' ' + GE.LASTNAME CONTACTNAME
		, GE.GLOBALENTITYNAME CONTACTCOMPANY
		, COALESCE(NULLIF(RTRIM(GE.BUSINESSPHONE),''), NULLIF(RTRIM(GE.MOBILEPHONE),''), NULLIF(RTRIM(GE.HOMEPHONE),''), NULLIF(RTRIM(GE.OTHERPHONE),'')) PHONE
		, GE.EMAIL
		, ROW_NUMBER () OVER (
			PARTITION BY PC.PMPERMITID, LMCT.[NAME]
			ORDER BY PC.ISBILLING DESC, PC.GLOBALENTITYID
			) ROWNBR
	FROM PMPERMITCONTACT PC
		INNER JOIN GLOBALENTITY GE ON PC.GLOBALENTITYID = GE.GLOBALENTITYID
		INNER JOIN LANDMANAGEMENTCONTACTTYPE LMCT ON PC.LANDMANAGEMENTCONTACTTYPEID = LMCT.LANDMANAGEMENTCONTACTTYPEID
	--WHERE PC.PMPERMITID = @PMPERMITID
), INSPECTIONS AS (
	SELECT WFS.PMPERMITID
		, WFS.[NAME] WFSTEPNAME
		, WFAS.[NAME] WFACTIONNAME, STAT.[NAME] [WFActionStatus]
		, WFAS.VERSIONNUMBER
		, WFAS.STARTDATE [WFStartDate], WFAS.ENDDATE [WFEndDate], WFAS.SORTORDER, WFAS.PRIORITYORDER
		, ROW_NUMBER() OVER (ORDER BY CASE WHEN STAT.[NAME] LIKE 'Passed' THEN 1
											WHEN STAT.[NAME] LIKE 'Partial Pass' THEN 2
											WHEN STAT.[NAME] LIKE 'Failed' THEN 3
											WHEN STAT.[NAME] LIKE 'Started' THEN 4
											WHEN STAT.[NAME] LIKE 'Not Started' THEN 5
											ELSE 10 END, NULLIF(WFAS.ENDDATE, '') DESC, WFAS.ENDDATE, NULLIF(WFAS.STARTDATE, '') DESC, WFAS.STARTDATE, WFAS.PRIORITYORDER, WFAS.SORTORDER) ROWNNBR
	FROM PMPERMITWFSTEP WFS
	INNER JOIN PMPERMITWFACTIONSTEP WFAS ON WFS.PMPERMITWFSTEPID = WFAS.PMPERMITWFSTEPID AND WFAS.WFACTIONTYPEID = 6
	INNER JOIN WORKFLOWSTATUS STAT ON WFAS.WORKFLOWSTATUSID = STAT.WORKFLOWSTATUSID
	--WHERE WFS.PMPERMITID = @PMPERMITID
), SPRINKLERSYSTEM AS (
	SELECT *
	FROM (
	SELECT 'Sprinkler System Type' SFIELDNAME, R.CUSTOMFIELDTABLEID, X.OBJECTID PMPERMITID, X.ROWNUMBER
				, CAST(I.SVALUE AS VARCHAR(200)) XVAL
			FROM CUSTOMFIELD C
				INNER JOIN CUSTOMFIELDCOLUMNTEMPLATE T ON C.GCUSTOMFIELD = T.GCUSTOMFIELD
				INNER JOIN CUSTOMFIELDTABLECOLUMNREF R ON T.CUSTOMFIELDCOLUMNTEMPLATEID = R.CUSTOMFIELDCOLUMNTEMPLATEID
				INNER JOIN CUSTOMSAVERTBLCOL_LST X ON R.CUSTOMFIELDTABLECOLUMNREFID = X.CFTABLECOLUMNREFID
				INNER JOIN CUSTOMFIELDPICKLISTITEM I ON X.PICKLISTVALUE = I.GCUSTOMFIELDPICKLISTITEM
			WHERE 
			--X.OBJECTID = @PMPERMITID
			--	AND 
				C.SFIELDNAME IN ( 'COLPCK_SprinklerSystemType' )
				AND R.CUSTOMFIELDTABLEID IN ( '9c85bce1-79bf-47df-a422-62a3cbb169ea' )

	UNION ALL

	SELECT 'New or Modification' SFIELDNAME, R.CUSTOMFIELDTABLEID, X.OBJECTID PMPERMITID, X.ROWNUMBER
				, CAST(I.SVALUE AS VARCHAR(200)) XVAL
			FROM CUSTOMFIELD C
				INNER JOIN CUSTOMFIELDCOLUMNTEMPLATE T ON C.GCUSTOMFIELD = T.GCUSTOMFIELD
				INNER JOIN CUSTOMFIELDTABLECOLUMNREF R ON T.CUSTOMFIELDCOLUMNTEMPLATEID = R.CUSTOMFIELDCOLUMNTEMPLATEID
				INNER JOIN CUSTOMSAVERTBLCOL_LST X ON R.CUSTOMFIELDTABLECOLUMNREFID = X.CFTABLECOLUMNREFID
				INNER JOIN CUSTOMFIELDPICKLISTITEM I ON X.PICKLISTVALUE = I.GCUSTOMFIELDPICKLISTITEM
			WHERE 
			--X.OBJECTID = @PMPERMITID
			--	AND 
				C.SFIELDNAME IN ( 'COLPCK_NewOrModification' )
				AND R.CUSTOMFIELDTABLEID IN ( '9c85bce1-79bf-47df-a422-62a3cbb169ea' )	
		) X
		PIVOT(MAX(X.XVAL) FOR X.SFIELDNAME IN ([Sprinkler System Type], [New or Modification])
		) P
		WHERE COALESCE([Sprinkler System Type], [New or Modification]) IS NOT NULL
	)
SELECT P.PMPERMITID, P.PERMITNUMBER, P.DESCRIPTION
	, PT.[NAME] PERMITTYPE, WC.[NAME] WORKCLASS
	, UPPER(RTRIM(LTRIM(COALESCE(MA.POBOX,'') + ' ')
		+ COALESCE(MA.ADDRESSLINE1,'') + ' ' 
		+ LTRIM(COALESCE(MA.PREDIRECTION,'') + ' ') 
		+ LTRIM(COALESCE(MA.ADDRESSLINE2,'') + ' ') 
		+ LTRIM(COALESCE(MA.STREETTYPE,'') + ' ') 
		+ LTRIM(COALESCE(MA.POSTDIRECTION,'') + ' ') 
		+ LTRIM(COALESCE(MA.UNITORSUITE,'') + ' ')) 
		+ ' TUC'
	  ) SITEADDRESS_LINE1
	, (CASE WHEN RTRIM(LTRIM(COALESCE(MA.CITY,''))) = '' 
			THEN '' 
			ELSE RTRIM(LTRIM(COALESCE(MA.CITY,''))) + ', ' END)
			+ (LTRIM(COALESCE(MA.[STATE],'') + ' ') 
			+ REPLACE((CASE WHEN LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ','')) > 5 
			THEN LEFT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),5) + '-' + RIGHT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),ABS(LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''))-5)) 
			ELSE COALESCE(MA.POSTALCODE,'') END),'--','-')
		  ) SITEADDRESS_LINE2
	, PAR.PARCELNUMBER
	, C.CONTACTNAME CONTRACTORNAME, C.CONTACTCOMPANY CONCOMPANY
	, I.WFACTIONNAME, I.VERSIONNUMBER, I.WFActionStatus
	, I.WFStartDate, I.WFEndDate
	, CASE WHEN WC.PMPERMITWORKCLASSID IN ('6ee7f902-cafe-4d68-8c87-b5ffe5ff3f22') 
						THEN STUFF((SELECT ', ' + SS.[Sprinkler System Type]
						FROM SPRINKLERSYSTEM SS
						WHERE SS.PMPERMITID = P.PMPERMITID
							AND NULLIF(RTRIM(SS.[Sprinkler System Type]), '') IS NOT NULL
						ORDER BY SS.ROWNUMBER
						FOR XML PATH(''), root('MyString'), type
						).value('/MyString[1]','varchar(max)'),1,2,''
						)
			WHEN WC.PMPERMITWORKCLASSID IN ('7e70317d-9fea-4d01-b9d2-4c6bc2d2928a') THEN dbo.GetMultiSelectValue(P.PMPERMITID, '2b205159-f6ca-499d-be4b-90f5e0b7b6d4') 
			WHEN WC.PMPERMITWORKCLASSID IN ('7f67816a-c801-4c79-90ee-9ec9facda5cb') THEN PI_OTHERSYSTEM.SVALUE
			WHEN WC.PMPERMITWORKCLASSID IN ('4dd99dcb-b633-4896-a8ab-7a787e22c1a8') THEN PI_STORAGETYPE.SVALUE
		END DESCRIPTIONOFWORK
	, (SELECT [IMAGE] FROM RPTIMAGELIB WHERE IMAGENAME = 'TucsonLogo') AS TucsonLogo
	, (SELECT [IMAGE] FROM RPTIMAGELIB WHERE IMAGENAME = 'TFDLogo') AS TFDLogo
FROM PMPERMIT P
	INNER JOIN PMPERMITTYPE PT ON P.PMPERMITTYPEID = PT.PMPERMITTYPEID
	INNER JOIN PMPERMITWORKCLASS WC ON P.PMPERMITWORKCLASSID = WC.PMPERMITWORKCLASSID
	LEFT JOIN PMPERMITADDRESS PA ON P.PMPERMITID = PA.PMPERMITID
		AND PA.MAIN = 1
	LEFT JOIN MAILINGADDRESS MA ON PA.MAILINGADDRESSID = MA.MAILINGADDRESSID
	LEFT JOIN PMPERMITPARCEL PPAR ON P.PMPERMITID = PPAR.PMPERMITID
		AND PPAR.MAIN = 1
	LEFT JOIN PARCEL PAR ON PPAR.PARCELID = PAR.PARCELID
	LEFT JOIN CONTACTS C ON P.PMPERMITID = C.PMPERMITID
		AND C.CONTACTTYPE = 'Contractor'
		AND C.ROWNBR = 1
	LEFT JOIN CUSTOMSAVERPERMITMANAGEMENT CS1 ON P.PMPERMITID = CS1.ID
	LEFT JOIN CUSTOMFIELDPICKLISTITEM PI_OTHERSYSTEM ON CS1.PCK_OthrFireConstructType = PI_OTHERSYSTEM.GCUSTOMFIELDPICKLISTITEM
	LEFT JOIN CUSTOMFIELDPICKLISTITEM PI_STORAGETYPE ON CS1.PCK_StorageTankType = PI_STORAGETYPE.GCUSTOMFIELDPICKLISTITEM
	LEFT JOIN INSPECTIONS I ON P.PMPERMITID = I.PMPERMITID
--WHERE P.PMPERMITID = @PMPERMITID
--ORDER BY I.ROWNNBR
--WHERE P.PERMITNUMBER = 'TF-FCP-0524-00354'
--END
--GO

--WHERE C.CONTACTNAME IS NULL AND C.CONTACTCOMPANY IS NOT NULL
