USE [EnerGov_Tucson_Prod]
--GO

--/****** Object:  StoredProcedure [dbo].[rpt_CoT_PM_FloodplainUsePermit]    Script Date: 8/11/2025 1:13:50 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO



--CREATE PROCEDURE [dbo].[rpt_CoT_PM_FloodplainUsePermit]
--	@PMPERMITID AS CHAR(36)
--AS

--BEGIN
--DECLARE @PMPERMITID AS CHAR(36) = '29584979-efb0-49ba-b8fc-391e679e628a';
--DECLARE @PMPERMITID AS CHAR(36) = '065F0BB9-0C7F-49E8-8FE8-4CE39AB132D4';

;WITH
	CONTACTS AS (
		SELECT PC.PMPERMITID, PC.GLOBALENTITYID
			, LMCT.[NAME] CONTACTTYPE
			, GE.FIRSTNAME + ' ' + GE.LASTNAME CONTACTNAME
			, GE.GLOBALENTITYNAME CONTACTCOMPANY
			, COALESCE(NULLIF(RTRIM(GE.BUSINESSPHONE),''), NULLIF(RTRIM(GE.MOBILEPHONE),''), NULLIF(RTRIM(GE.HOMEPHONE),''), NULLIF(RTRIM(GE.OTHERPHONE),'')) PHONE
			, GE.EMAIL
			, ROW_NUMBER () OVER (
				PARTITION BY PC.PMPERMITID, LMCT.[NAME]
				ORDER BY PC.ISBILLING DESC, PC.GLOBALENTITYID
			  ) ROWNBR
		FROM PMPERMITCONTACT PC
			INNER JOIN GLOBALENTITY GE ON PC.GLOBALENTITYID = GE.GLOBALENTITYID
			INNER JOIN LANDMANAGEMENTCONTACTTYPE LMCT ON PC.LANDMANAGEMENTCONTACTTYPEID = LMCT.LANDMANAGEMENTCONTACTTYPEID
		--WHERE PC.PMPERMITID = @PMPERMITID
	), CONADD AS (
		SELECT C.GLOBALENTITYID
		, RTRIM(RTRIM(LTRIM(COALESCE(MA.POBOX,'') + ' ')
			+ LTRIM(COALESCE(MA.ADDRESSLINE1,'') + ' ')
			+ LTRIM(COALESCE(MA.PREDIRECTION,'') + ' ') 
			+ LTRIM(COALESCE(MA.ADDRESSLINE2,'') + ' ') 
			+ LTRIM(COALESCE(MA.STREETTYPE,'') + ' ') 
			+ LTRIM(COALESCE(MA.POSTDIRECTION,'') + ' ')
		  )
			+ CASE WHEN NULLIF(RTRIM(MA.UNITORSUITE),'') IS NOT NULL
					THEN CHAR(10) + LTRIM(COALESCE(MA.UNITORSUITE,'') + ' ') 
					ELSE ''
			  END
			--+ LTRIM(COALESCE(MA.ADDRESSLINE3,''))
		  ) AL1
		, (CASE WHEN RTRIM(LTRIM(COALESCE(MA.CITY,''))) = '' 
			THEN '' 
			ELSE RTRIM(LTRIM(COALESCE(MA.CITY,''))) + ', ' END)
			+ (LTRIM(COALESCE(MA.[STATE],'') + ' ') 
			+ REPLACE((CASE WHEN LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ','')) > 5 
			THEN LEFT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),5) + '-' + RIGHT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),ABS(LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''))-5)) 
			ELSE COALESCE(MA.POSTALCODE,'') END),'--','-')
		  ) AL2
		  , ROW_NUMBER () OVER (
			PARTITION BY C.GLOBALENTITYID
			ORDER BY GEMA.MAIN DESC, MA.MAILINGADDRESSID
		  ) ROWNBR
	FROM CONTACTS C
	INNER JOIN GLOBALENTITYMAILINGADDRESS GEMA ON C.GLOBALENTITYID = GEMA.GLOBALENTITYID
	INNER JOIN MAILINGADDRESS MA ON GEMA.MAILINGADDRESSID = MA.MAILINGADDRESSID
), PARENTPERMITNUMBER AS (
SELECT P.PMPERMITID, P.PERMITNUMBER, PM.PERMITNUMBER PARENTPERMITNUMBER, PM.PMPERMITID PARENTPERMITID
FROM PMPERMIT P
INNER JOIN PMPERMITACTIONREF AR ON P.PMPERMITID = AR.PMPERMITID
INNER JOIN PMPERMITWFACTIONSTEP WFAS ON AR.OBJECTID = WFAS.PMPERMITWFACTIONSTEPID
INNER JOIN PMPERMITWFSTEP WFS ON WFAS.PMPERMITWFSTEPID = WFS.PMPERMITWFSTEPID
INNER JOIN PMPERMIT PM ON WFS.PMPERMITID = PM.PMPERMITID
--WHERE P.PMPERMITID = @PMPERMITID
)
SELECT P.PMPERMITID, P.PERMITNUMBER, P.[DESCRIPTION] PERMITDESCRIPTION
	, P.ISSUEDATE, P.[EXPIREDATE]
	, UPPER(PT.NAME) PERMITTYPE, UPPER(PWC.NAME) TYPEOFAPPLICATION
	, A.CONTACTNAME APPLICANTNAME, A.PHONE APPPHONE, A.CONTACTCOMPANY APPCOMPANY
	, UPPER(AA.AL1) APP_AL1, UPPER(AA.AL2) APP_AL2
	, O.CONTACTNAME OWNERNAME, O.PHONE OWNPHONE, O.CONTACTCOMPANY OWNCOMPANY
	, UPPER(OA.AL1) OWN_AL1, UPPER(OA.AL2) OWN_AL2
	, UPPER(RTRIM(LTRIM(COALESCE(MA.POBOX,'') + ' ')
		+ LTRIM(COALESCE(MA.ADDRESSLINE1,'') + ' ') 
		+ LTRIM(COALESCE(MA.PREDIRECTION,'') + ' ') 
		+ LTRIM(COALESCE(MA.ADDRESSLINE2,'') + ' ') 
		+ LTRIM(COALESCE(MA.STREETTYPE,'') + ' ') 
		+ LTRIM(COALESCE(MA.POSTDIRECTION,'') + ' ') 
		+ LTRIM(COALESCE(MA.UNITORSUITE,'') + ' ') 
		+ ' TUC')
	  ) SITEADDRESS_LINE1
	, (CASE WHEN RTRIM(LTRIM(COALESCE(MA.CITY,''))) = '' 
			THEN '' 
			ELSE RTRIM(LTRIM(COALESCE(MA.CITY,''))) + ', ' END)
			+ (LTRIM(COALESCE(MA.[STATE],'') + ' ') 
			+ REPLACE((CASE WHEN LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ','')) > 5 
			THEN LEFT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),5) + '-' + RIGHT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),ABS(LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''))-5)) 
			ELSE COALESCE(MA.POSTALCODE,'') END),'--','-')
		  ) SITEADDRESS_LINE2
	, PAR.PARCELNUMBER
	, D.[NAME] WARD
	, STUFF((SELECT ', ' + PPN.PARENTPERMITNUMBER FROM PARENTPERMITNUMBER PPN 
			WHERE PPN.PMPERMITID = P.PMPERMITID
			FOR XML PATH('')
			), 1, 1, '') PARENTPERMITNUMBER
	, CS1.AUTOTXT_LegalDescrip LEGALDESCRIPTION
	, CS1.AUTOTXT_Twnshp_Sect_Range TRS
	, PI_FloodZone.SVALUE FloodZone
	, CS1.AUTOTXT_FIRMMapPanel
	, CS1.TXT_WASHNAME
	, CS1.MON_OriginalValuation
	, CS1.MON_WorkValuation
	, CS1.TXT_ValuationSourceDesc
	, CS1.CALC_WorkValueVSOrigBldg
	, CS1.PCK_ElevationDatum
	, CS1.TXT_OtherCoordSystem
	, CS1.NUM_BaseFloodElevation
	, (SELECT [IMAGE] FROM RPTIMAGELIB WHERE IMAGENAME = 'TucsonTRLogo') AS TucsonLogo
FROM PMPERMIT P
	LEFT JOIN DISTRICT D ON P.DISTRICTID = D.DISTRICTID
	LEFT JOIN PMPERMITADDRESS PA ON P.PMPERMITID = PA.PMPERMITID
		AND PA.MAIN = 1
	LEFT JOIN MAILINGADDRESS MA ON PA.MAILINGADDRESSID = MA.MAILINGADDRESSID
	LEFT JOIN PMPERMITPARCEL PPAR ON P.PMPERMITID = PPAR.PMPERMITID
		AND PPAR.MAIN = 1
	LEFT JOIN PARCEL PAR ON PPAR.PARCELID = PAR.PARCELID
	INNER JOIN PMPERMITTYPE PT ON P.PMPERMITTYPEID = PT.PMPERMITTYPEID
	INNER JOIN PMPERMITWORKCLASS PWC ON P.PMPERMITWORKCLASSID = PWC.PMPERMITWORKCLASSID
	LEFT JOIN CONTACTS A ON P.PMPERMITID = A.PMPERMITID
		AND A.CONTACTTYPE = 'Applicant'
		AND A.ROWNBR = 1
	LEFT JOIN CONADD AA ON A.GLOBALENTITYID = AA.GLOBALENTITYID
		AND AA.ROWNBR = 1
	LEFT JOIN CONTACTS O ON P.PMPERMITID = O.PMPERMITID
		AND O.CONTACTTYPE = 'Owner'
		AND O.ROWNBR = 1
	LEFT JOIN CONADD OA ON O.GLOBALENTITYID = OA.GLOBALENTITYID
		AND OA.ROWNBR = 1
	LEFT JOIN CUSTOMSAVERPERMITMANAGEMENT CS1 ON P.PMPERMITID = CS1.ID
	LEFT JOIN CUSTOMFIELDPICKLISTITEM PI_FloodZone ON CS1.PCK_FloodZone = PI_FloodZone.GCUSTOMFIELDPICKLISTITEM
	LEFT JOIN PMPERMIT PARENTPERMIT ON P.PMPERMITPARENTID = PARENTPERMIT.PMPERMITID
--WHERE P.PMPERMITID = @PMPERMITID


--END
--GO

--(1) 
--WHERE P.PERMITNUMBER = 'T22MH00040'
--WHERE P.PMPERMITID = '0044C41D-0961-4843-92F0-A6DDD41A317C'

--(2) CS1.NUM_BaseFloodElevation IS NULL
--WHERE P.PERMITNUMBER = 'TF-FOP-0823-01331'
--WHERE P.PMPERMITID = '0009f451-fcfa-4362-a475-e963f9b336c6'

--(3) Floodplain Use Permit with Elevation Certificate
--WHERE P.PERMITNUMBER = 'TE-FPU-0823-00299'
--WHERE P.PMPERMITID = '6fca7e77-487f-406d-a059-0aaff8e53534'

--(4) FIMRMapPanel and WorkValuation
--WHERE P.PERMITNUMBER = 'TE-FPU-0923-00335'
--WHERE P.PMPERMITID = '02f0568b-2212-4f9f-aa7e-d28566ad117a'
