USE [EnerGov_Tucson_Prod]
--GO

--/****** Object:  StoredProcedure [dbo].[rpt_PL_EntitlementsClosureLetter]    Script Date: 8/12/2025 5:39:11 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO






----CREATE PROCEDURE [dbo].[rpt_PL_EntitlementsClosureLetter]
--CREATE PROCEDURE [dbo].[rpt_PL_EntitlementsClosureLetter]
--	@PLPLANID AS CHAR(36)
--AS

--BEGIN
--DECLARE @PLPLANID AS CHAR(36) = '944ce985-fd6f-4ecd-b675-cf529fa6a9b0';

;WITH
	CONTACTS AS (
		SELECT PC.PLPLANID, PC.GLOBALENTITYID
			, LMCT.[NAME] CONTACTTYPE
			, CASE WHEN NULLIF(RTRIM(GE.FIRSTNAME + GE.LASTNAME), '') IS NULL
				THEN GE.GLOBALENTITYNAME
				ELSE GE.FIRSTNAME + ' ' + GE.LASTNAME
			END CONTACTNAME
		, COALESCE(NULLIF(RTRIM(GE.BUSINESSPHONE),''), NULLIF(RTRIM(GE.MOBILEPHONE),''), NULLIF(RTRIM(GE.HOMEPHONE),''), NULLIF(RTRIM(GE.OTHERPHONE),'')) PHONE
		, GE.EMAIL
		, ROW_NUMBER () OVER (
			PARTITION BY PC.PLPLANID, LMCT.[NAME]
			ORDER BY PC.ISBILLING DESC, PC.GLOBALENTITYID
		  ) ROWNBR
		FROM PLPLANCONTACT PC
			INNER JOIN GLOBALENTITY GE ON PC.GLOBALENTITYID = GE.GLOBALENTITYID
			INNER JOIN LANDMANAGEMENTCONTACTTYPE LMCT ON PC.LANDMANAGEMENTCONTACTTYPEID = LMCT.LANDMANAGEMENTCONTACTTYPEID
		--WHERE PC.PLPLANID = @PLPLANID
	), CONADD AS (
		SELECT C.GLOBALENTITYID
		, RTRIM(RTRIM(LTRIM(COALESCE(MA.POBOX,'') + ' ')
			+ LTRIM(COALESCE(MA.ADDRESSLINE1,'') + ' ')
			+ LTRIM(COALESCE(MA.PREDIRECTION,'') + ' ') 
			+ LTRIM(COALESCE(MA.ADDRESSLINE2,'') + ' ') 
			+ LTRIM(COALESCE(MA.STREETTYPE,'') + ' ') 
			+ LTRIM(COALESCE(MA.POSTDIRECTION,'') + ' ')
		  )
			+ CASE WHEN NULLIF(RTRIM(MA.UNITORSUITE),'') IS NOT NULL
					THEN CHAR(10) + LTRIM(COALESCE(MA.UNITORSUITE,'') + ' ') 
					ELSE ''
			  END
			--+ LTRIM(COALESCE(MA.ADDRESSLINE3,''))
		  ) AL1
		, (CASE WHEN RTRIM(LTRIM(COALESCE(MA.CITY,''))) = '' 
			THEN '' 
			ELSE RTRIM(LTRIM(COALESCE(MA.CITY,''))) + ', ' END)
			+ (LTRIM(COALESCE(MA.[STATE],'') + ' ') 
			+ REPLACE((CASE WHEN LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ','')) > 5 
			THEN LEFT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),5) + '-' + RIGHT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),ABS(LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''))-5)) 
			ELSE COALESCE(MA.POSTALCODE,'') END),'--','-')
		  ) AL2
		  , ROW_NUMBER () OVER (
			PARTITION BY C.GLOBALENTITYID
			ORDER BY GEMA.MAIN DESC, MA.MAILINGADDRESSID
		  ) ROWNBR
	FROM CONTACTS C
	INNER JOIN GLOBALENTITYMAILINGADDRESS GEMA ON C.GLOBALENTITYID = GEMA.GLOBALENTITYID
	INNER JOIN MAILINGADDRESS MA ON GEMA.MAILINGADDRESSID = MA.MAILINGADDRESSID
	), WFHEARING AS (
	SELECT WFS.PLPLANID
		, H.STARTDATE
	FROM PLPLANWFSTEP WFS
		INNER JOIN PLPLANWFACTIONSTEP WFAS ON WFS.PLPLANWFSTEPID = WFAS.PLPLANWFSTEPID
			AND WFAS.NAME IN ( 'Mayor and Council Public Hearing' )
		INNER JOIN HEARINGXREF HXR ON WFAS.PLPLANWFACTIONSTEPID = HXR.OBJECTID
		INNER JOIN HEARING H ON HXR.HEARINGID = H.HEARINGID
			AND H.HEARINGSTATUSID IN (
				'945ba98e-3ca6-4fa7-b583-95b7785efef6' --Closed
				, 'ad0d32d5-ddcf-48cc-9d28-9c0b68a5753e' --Scheduled
			)
		INNER JOIN HEARINGTYPE HT ON H.HEARINGTYPEID = HT.HEARINGTYPEID
		INNER JOIN HEARINGSTATUS HS ON H.HEARINGSTATUSID = HS.HEARINGSTATUSID
	--WHERE WFS.PLPLANID = @PLPLANID
	), PLANACTIVITY AS (
		SELECT PLA.PLPLANACTIVITYID, PLA.PLPLANID, PLA.PLANACTIVITYNUMBER, PLA.PLPLANACTIVITYTYPEID
			,  CS.TXT_OrdinanceNumber, CS.DAT_OrdinanceDate, CS.DAT_AuthorizationDate, PI_CLOSURETYPE.SVALUE CLOSURETYPE
			, CS.DAT_CaseClosed
		FROM PLPLANACTIVITY PLA
			LEFT JOIN CUSTOMSAVERPLANMANAGEMENT CS ON PLA.PLPLANACTIVITYID = CS.ID
			LEFT JOIN CUSTOMFIELDPICKLISTITEM PI_CLOSURETYPE ON CS.PCK_ClosureType = PI_CLOSURETYPE.GCUSTOMFIELDPICKLISTITEM
		--WHERE PLA.PLPLANID = @PLPLANID
	)
SELECT P.PLPLANID
	, P.DESCRIPTION, P.PLANNUMBER
	, PWC.NAME WORKCLASS
	, A.CONTACTNAME
	, AA.AL1
	, AA.AL2
	, H.STARTDATE HearingDate
	, CLOSURETYPE.CLOSURETYPE CLOSURETYPE
	, ORDINANCE.TXT_OrdinanceNumber ORDINANCENUMBER
	, ORDINANCE.DAT_AuthorizationDate EFFECTUATIONDATE
	, REPLACE(STUFF((SELECT ', ' + PI_ZoningCategories.SVALUE
		FROM CUSTOMFIELD C
			INNER JOIN CUSTOMFIELDCOLUMNTEMPLATE T ON C.GCUSTOMFIELD = T.GCUSTOMFIELD
			INNER JOIN CUSTOMFIELDTABLECOLUMNREF R ON T.CUSTOMFIELDCOLUMNTEMPLATEID = R.CUSTOMFIELDCOLUMNTEMPLATEID
			INNER JOIN CUSTOMSAVERTBLCOL_LST X ON R.CUSTOMFIELDTABLECOLUMNREFID = X.CFTABLECOLUMNREFID
			INNER JOIN CUSTOMFIELDPICKLISTITEM PI_ZoningCategories ON X.PICKLISTVALUE = PI_ZoningCategories.GCUSTOMFIELDPICKLISTITEM
		WHERE 
		--X.OBJECTID = @PLPLANID
		--	AND 
			C.SFIELDNAME IN ( 'COLPCK_ZoningCategories' )
			AND R.CUSTOMFIELDTABLEID IN ( '13df8b21-51d3-42f6-8c6c-bdf853404f0e' )
		FOR XML PATH(''),root('MyString'),type).value('/MyString[1]','varchar(max)'), 1, 2,''), ', ', ', ') ProposedZoning
	--, (SELECT REPORTTEXT FROM RPTTEXTLIB WHERE TEXTNAME = '') AS 
	, (SELECT [IMAGE] FROM RPTIMAGELIB WHERE IMAGENAME = 'TucsonLogo') AS TucsonLogo

FROM PLPLAN P
	LEFT JOIN PLPLANWORKCLASS PWC ON P.PLPLANWORKCLASSID = PWC.PLPLANWORKCLASSID
	LEFT JOIN CONTACTS A ON P.PLPLANID = A.PLPLANID
		AND A.CONTACTTYPE = 'Applicant'
	LEFT JOIN CONADD AA ON A.GLOBALENTITYID = AA.GLOBALENTITYID
		AND AA.ROWNBR = 1
	LEFT JOIN WFHEARING H ON P.PLPLANID = H.PLPLANID
	LEFT JOIN CUSTOMSAVERPLANMANAGEMENT CSPM ON P.PLPLANID = CSPM.ID
	LEFT JOIN PLANACTIVITY CLOSURETYPE ON P.PLPLANID = CLOSURETYPE.PLPLANID
		AND CLOSURETYPE.PLPLANACTIVITYTYPEID = '8b6e67fc-db9f-4eb4-89e0-9e951fad9e8b'
	LEFT JOIN PLANACTIVITY ORDINANCE ON P.PLPLANID = ORDINANCE.PLPLANID
		AND ORDINANCE.PLPLANACTIVITYTYPEID = 'd5088981-edfa-435f-bb77-6e97bea9005c'
--WHERE P.PLPLANID = @PLPLANID
--WHERE A.CONTACTNAME IS NOT NULL
--AND H.STARTDATE IS NOT NULL

--(1) Contact Info
--WHERE P.PLANNUMBER = 'C9-22-09'
--WHERE P.PLPLAINID = '441E2BDB-6E46-40D6-B1C0-EB1BA08963DA'

--(2) Ordinance Number
--WHERE P.PLANNUMBER = 'TP-AMD-0523-00004'
--WHERE P.PLPLAINID = '8f0e3ba5-2036-4399-ad73-6c0a5c038680'

--(3) Hearing Date
--WHERE P.PLANNUMBER = 'T13SE00092'
--WHERE P.PLPLAINID = 'E8F0EF58-EA68-48A6-AAAE-FA85AC4097AD'

--(4) Effectuation Date
--WHERE P.PLANNUMBER = 'TP-ENT-0423-00019'
--WHERE P.PLPLAINID = '81a2ed57-48df-4859-bbac-44b9ca817f80'














--END
--GO




