USE [EnerGov_Tucson_Prod]
--GO

--/****** Object:  StoredProcedure [dbo].[rpt_PDSD_JobCard]    Script Date: 8/10/2025 2:16:56 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO


--CREATE PROCEDURE [dbo].[rpt_PDSD_JobCard]
--	@PMPERMITID AS CHAR(36)
--AS

--BEGIN
--DECLARE @PMPERMITID AS CHAR(36) = '21a84e65-e7ca-4abb-a8d6-8685d79cd51f';
;WITH
CONTACTS AS (
	SELECT PC.PMPERMITID, PC.GLOBALENTITYID
		, LMCT.[NAME] CONTACTTYPE
		, GE.FIRSTNAME + ' ' + GE.LASTNAME CONTACTNAME
		, GE.GLOBALENTITYNAME CONTACTCOMPANY
		, COALESCE(NULLIF(RTRIM(GE.BUSINESSPHONE),''), NULLIF(RTRIM(GE.MOBILEPHONE),''), NULLIF(RTRIM(GE.HOMEPHONE),''), NULLIF(RTRIM(GE.OTHERPHONE),'')) PHONE
		, GE.EMAIL
		, ROW_NUMBER () OVER (
			PARTITION BY PC.PMPERMITID, LMCT.[NAME]
			ORDER BY PC.ISBILLING DESC, PC.GLOBALENTITYID
			) ROWNBR
	FROM PMPERMITCONTACT PC
		INNER JOIN GLOBALENTITY GE ON PC.GLOBALENTITYID = GE.GLOBALENTITYID
		INNER JOIN LANDMANAGEMENTCONTACTTYPE LMCT ON PC.LANDMANAGEMENTCONTACTTYPEID = LMCT.LANDMANAGEMENTCONTACTTYPEID
	--WHERE PC.PMPERMITID = @PMPERMITID
), CONADD AS (
		SELECT C.GLOBALENTITYID
		, RTRIM(RTRIM(LTRIM(COALESCE(MA.POBOX,'') + ' ')
			+ LTRIM(COALESCE(MA.ADDRESSLINE1,'') + ' ')
			+ LTRIM(COALESCE(MA.PREDIRECTION,'') + ' ') 
			+ LTRIM(COALESCE(MA.ADDRESSLINE2,'') + ' ') 
			+ LTRIM(COALESCE(MA.STREETTYPE,'') + ' ') 
			+ LTRIM(COALESCE(MA.POSTDIRECTION,'') + ' ')
		  )
			+ CASE WHEN NULLIF(RTRIM(MA.UNITORSUITE),'') IS NOT NULL
					THEN CHAR(10) + LTRIM(COALESCE(MA.UNITORSUITE,'') + ' ') 
					ELSE ''
			  END
			--+ LTRIM(COALESCE(MA.ADDRESSLINE3,''))
		  ) AL1
		, (CASE WHEN RTRIM(LTRIM(COALESCE(MA.CITY,''))) = '' 
			THEN '' 
			ELSE RTRIM(LTRIM(COALESCE(MA.CITY,''))) + ', ' END)
			+ (LTRIM(COALESCE(MA.[STATE],'') + ' ') 
			+ REPLACE((CASE WHEN LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ','')) > 5 
			THEN LEFT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),5) + '-' + RIGHT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),ABS(LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''))-5)) 
			ELSE COALESCE(MA.POSTALCODE,'') END),'--','-')
		  ) AL2
		  , ROW_NUMBER () OVER (
			PARTITION BY C.GLOBALENTITYID
			ORDER BY GEMA.MAIN DESC, MA.MAILINGADDRESSID
		  ) ROWNBR
	FROM CONTACTS C
	INNER JOIN GLOBALENTITYMAILINGADDRESS GEMA ON C.GLOBALENTITYID = GEMA.GLOBALENTITYID
	INNER JOIN MAILINGADDRESS MA ON GEMA.MAILINGADDRESSID = MA.MAILINGADDRESSID
), INSPECTIONS AS (
	SELECT WFS.PMPERMITID
		, WFS.[NAME] WFSTEPNAME
		, WFAS.[NAME] WFACTIONNAME, WFAS.VERSIONNUMBER, STAT.[NAME] [WFActionStatus]
		, WFAS.STARTDATE [WFStartDate], WFAS.ENDDATE [WFEndDate], WFAS.SORTORDER, WFAS.PRIORITYORDER
		, ROW_NUMBER() OVER (ORDER BY CASE WHEN STAT.[NAME] LIKE 'Passed' THEN 1
											WHEN STAT.[NAME] LIKE 'Partial Pass' THEN 2
											WHEN STAT.[NAME] LIKE 'Failed' THEN 3
											WHEN STAT.[NAME] LIKE 'Started' THEN 4
											WHEN STAT.[NAME] LIKE 'Not Started' THEN 5
											ELSE 10 END, NULLIF(WFAS.ENDDATE, '') DESC, WFAS.ENDDATE, NULLIF(WFAS.STARTDATE, '') DESC, WFAS.STARTDATE, WFAS.PRIORITYORDER, WFAS.SORTORDER) ROWNNBR
	FROM PMPERMITWFSTEP WFS
	INNER JOIN PMPERMITWFACTIONSTEP WFAS ON WFS.PMPERMITWFSTEPID = WFAS.PMPERMITWFSTEPID AND WFAS.WFACTIONTYPEID = 6
	INNER JOIN WORKFLOWSTATUS STAT ON WFAS.WORKFLOWSTATUSID = STAT.WORKFLOWSTATUSID
	--WHERE WFS.PMPERMITID = @PMPERMITID
	)

SELECT P.PMPERMITID, P.PERMITNUMBER
	, UPPER(RTRIM(LTRIM(COALESCE(MA.POBOX,'') + ' ')
		+ COALESCE(MA.ADDRESSLINE1,'') + ' ' 
		+ LTRIM(COALESCE(MA.PREDIRECTION,'') + ' ') 
		+ LTRIM(COALESCE(MA.ADDRESSLINE2,'') + ' ') 
		+ LTRIM(COALESCE(MA.STREETTYPE,'') + ' ') 
		+ LTRIM(COALESCE(MA.POSTDIRECTION,'') + ' ') 
		+ LTRIM(COALESCE(MA.UNITORSUITE,'') + ' ')) 
		+ ' TUC'
	  ) SITEADDRESS_LINE1
	, (CASE WHEN RTRIM(LTRIM(COALESCE(MA.CITY,''))) = '' 
			THEN '' 
			ELSE RTRIM(LTRIM(COALESCE(MA.CITY,''))) + ', ' END)
			+ (LTRIM(COALESCE(MA.[STATE],'') + ' ') 
			+ REPLACE((CASE WHEN LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ','')) > 5 
			THEN LEFT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),5) + '-' + RIGHT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),ABS(LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''))-5)) 
			ELSE COALESCE(MA.POSTALCODE,'') END),'--','-')
		  ) SITEADDRESS_LINE2
	, PAR.PARCELNUMBER
	, A.CONTACTNAME APPLICANTNAME, A.CONTACTCOMPANY APPCOMPANY, UPPER(AA.AL1) APP_AL1, UPPER(AA.AL2) APP_AL2
	, C.CONTACTNAME CONTRACTORNAME, C.CONTACTCOMPANY CONCOMPANY, UPPER(CA.AL1) CON_AL1, UPPER(CA.AL2) CON_AL2
	, CS1.TXT_StaffDescription DESCRIPTIONPROPOSEDWORK
	, CASE WHEN I.WFSTEPNAME LIKE 'Final Inspections' OR I.WFACTIONNAME LIKE '%FINAL%' THEN 'Final Inspections' ELSE 'Inspections' END INSPECTIONGROUP
	, I.WFACTIONNAME, I.VERSIONNUMBER, I.WFActionStatus
	, I.WFStartDate
	, I.WFEndDate
	--, CASE WHEN I.DUPROW + 1 = LEAD(I.DUPROW, 1,0)OVER (ORDER BY I.ROWNUMBER) THEN I.COMMENTS + CHAR(10) + 'Comment ' + CAST(I.DUPROW + 1 AS VARCHAR(1)) + ': '+ LEAD(I.COMMENTS,1,0) OVER (ORDER BY I.ROWNUMBER) ELSE I.COMMENTS END COMMENTS
	, (SELECT [IMAGE] FROM RPTIMAGELIB WHERE IMAGENAME = 'TucsonPDSDLogo') AS TucsonLogo
	, (SELECT [IMAGE] FROM RPTIMAGELIB WHERE IMAGENAME = 'TucsonLogo') AS TucsonLogoSmall
FROM PMPERMIT P
	LEFT JOIN PMPERMITADDRESS PA ON P.PMPERMITID = PA.PMPERMITID
		AND PA.MAIN = 1
	LEFT JOIN MAILINGADDRESS MA ON PA.MAILINGADDRESSID = MA.MAILINGADDRESSID
	LEFT JOIN PMPERMITPARCEL PPAR ON P.PMPERMITID = PPAR.PMPERMITID
		AND PPAR.MAIN = 1
	LEFT JOIN PARCEL PAR ON PPAR.PARCELID = PAR.PARCELID
	LEFT JOIN CONTACTS C ON P.PMPERMITID = C.PMPERMITID
		AND C.CONTACTTYPE = 'Contractor'
		AND C.ROWNBR = 1
	LEFT JOIN CONADD CA ON C.GLOBALENTITYID = CA.GLOBALENTITYID
		AND CA.ROWNBR = 1
	LEFT JOIN CONTACTS A ON P.PMPERMITID = A.PMPERMITID
		AND A.CONTACTTYPE = 'Applicant'
		AND A.ROWNBR = 1
	LEFT JOIN CONADD AA ON A.GLOBALENTITYID = AA.GLOBALENTITYID
		AND AA.ROWNBR = 1
	LEFT JOIN CUSTOMSAVERPERMITMANAGEMENT CS1 ON P.PMPERMITID = CS1.ID
	LEFT JOIN INSPECTIONS I ON P.PMPERMITID = I.PMPERMITID
--WHERE P.PMPERMITID = @PMPERMITID

--(1)
--WHERE P.PERMITNUMBER = 'T21OT00077'
--WHERE P.PMPERMITID = '001031B8-6A0B-4114-A29E-F9F2359E0493'

--(2) Version Number = 2
--WHERE P.PERMITNUMBER = 'TC-RES-0523-05473'
--WHERE P.PMPERMITID = '35b12bf4-2ed4-463d-9a1d-3c9f42a29491'

--(3) Version Number = 1
--WHERE P.PERMITNUMBER = 'TF-FOP-0823-01390'
--WHERE P.PMPERMITID = 'c596a72e-7af1-4edc-bdc1-52f59185c495'

--(4) Description Proposed Work
--WHERE P.PERMITNUMBER = 'TZ-PMT-0523-00049'
--WHERE P.PMPERMITID = '0ebecbd2-96a9-4df3-b17d-c28b1efca391'





ORDER BY CASE WHEN I.WFSTEPNAME LIKE 'Final Inspections' OR I.WFACTIONNAME LIKE '%FINAL%' THEN 5 ELSE 1 END, I.ROWNNBR


--END
--GO


