USE [EnerGov_Tucson_Prod]
--GO

--/****** Object:  StoredProcedure [dbo].[rpt_PDSD_Permit]    Script Date: 8/10/2025 11:35:33 AM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO


--CREATE PROCEDURE [dbo].[rpt_PDSD_Permit]
--	@PMPERMITID AS CHAR(36)
--AS

--BEGIN
--DECLARE @PMPERMITID AS CHAR(36) = '70d73294-0dd0-4926-9b76-25c02f55bda1';

;WITH
	CONTACTS AS (
		SELECT PC.PMPERMITID, PC.GLOBALENTITYID
			, LMCT.[NAME] CONTACTTYPE
			, GE.FIRSTNAME + ' ' + GE.LASTNAME CONTACTNAME
			, GE.GLOBALENTITYNAME CONTACTCOMPANY
			, COALESCE(NULLIF(RTRIM(GE.BUSINESSPHONE),''), NULLIF(RTRIM(GE.MOBILEPHONE),''), NULLIF(RTRIM(GE.HOMEPHONE),''), NULLIF(RTRIM(GE.OTHERPHONE),'')) PHONE
			, GE.EMAIL
			, ROW_NUMBER () OVER (
				PARTITION BY PC.PMPERMITID, LMCT.[NAME]
				ORDER BY PC.ISBILLING DESC, PC.GLOBALENTITYID
			  ) ROWNBR
		FROM PMPERMITCONTACT PC
			INNER JOIN GLOBALENTITY GE ON PC.GLOBALENTITYID = GE.GLOBALENTITYID
			INNER JOIN LANDMANAGEMENTCONTACTTYPE LMCT ON PC.LANDMANAGEMENTCONTACTTYPEID = LMCT.LANDMANAGEMENTCONTACTTYPEID
		--WHERE PC.PMPERMITID = @PMPERMITID
	), CONADD AS (
		SELECT C.GLOBALENTITYID
		, RTRIM(RTRIM(LTRIM(COALESCE(MA.POBOX,'') + ' ')
			+ LTRIM(COALESCE(MA.ADDRESSLINE1,'') + ' ')
			+ LTRIM(COALESCE(MA.PREDIRECTION,'') + ' ') 
			+ LTRIM(COALESCE(MA.ADDRESSLINE2,'') + ' ') 
			+ LTRIM(COALESCE(MA.STREETTYPE,'') + ' ') 
			+ LTRIM(COALESCE(MA.POSTDIRECTION,'') + ' ')
		  )
			+ CASE WHEN NULLIF(RTRIM(MA.UNITORSUITE),'') IS NOT NULL
					THEN CHAR(10) + LTRIM(COALESCE(MA.UNITORSUITE,'') + ' ') 
					ELSE ''
			  END
			--+ LTRIM(COALESCE(MA.ADDRESSLINE3,''))
		  ) AL1
		, (CASE WHEN RTRIM(LTRIM(COALESCE(MA.CITY,''))) = '' 
			THEN '' 
			ELSE RTRIM(LTRIM(COALESCE(MA.CITY,''))) + ', ' END)
			+ (LTRIM(COALESCE(MA.[STATE],'') + ' ') 
			+ REPLACE((CASE WHEN LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ','')) > 5 
			THEN LEFT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),5) + '-' + RIGHT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),ABS(LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''))-5)) 
			ELSE COALESCE(MA.POSTALCODE,'') END),'--','-')
		  ) AL2
		  , ROW_NUMBER () OVER (
			PARTITION BY C.GLOBALENTITYID
			ORDER BY GEMA.MAIN DESC, MA.MAILINGADDRESSID
		  ) ROWNBR
	FROM CONTACTS C
	INNER JOIN GLOBALENTITYMAILINGADDRESS GEMA ON C.GLOBALENTITYID = GEMA.GLOBALENTITYID
	INNER JOIN MAILINGADDRESS MA ON GEMA.MAILINGADDRESSID = MA.MAILINGADDRESSID
), NUMSTORIES AS (
SELECT P.*, CAST(P.[Above Grade Level] AS INT) + CAST(P.[Below Grade Level] AS INT) NumStories
FROM (
SELECT 'Above Grade Level' SFIELDNAME
	, R.CUSTOMFIELDTABLEID
	, X.OBJECTID PMPERMITID, X.ROWNUMBER
	, CAST(X.INTVALUE AS VARCHAR(200)) XVAL
FROM CUSTOMFIELD C
INNER JOIN CUSTOMFIELDCOLUMNTEMPLATE T ON C.GCUSTOMFIELD = T.GCUSTOMFIELD
INNER JOIN CUSTOMFIELDTABLECOLUMNREF R ON T.CUSTOMFIELDCOLUMNTEMPLATEID = R.CUSTOMFIELDCOLUMNTEMPLATEID
INNER JOIN CUSTOMSAVERTBLCOL_INT X ON R.CUSTOMFIELDTABLECOLUMNREFID = X.CFTABLECOLUMNREFID
WHERE 
	--X.OBJECTID = @PMPERMITID		
	--AND 
	C.SFIELDNAME IN ('COLNUM_AboveGradeLevels')
	AND R.CUSTOMFIELDTABLEID IN ('489e9435-597b-412d-a296-5e8a1f9ffdc5') 

UNION ALL

SELECT 'Below Grade Level' SFIELDNAME
	, R.CUSTOMFIELDTABLEID
	, X.OBJECTID PMPERMITID, X.ROWNUMBER
	, CAST(X.INTVALUE AS VARCHAR(200)) XVAL
FROM CUSTOMFIELD C
INNER JOIN CUSTOMFIELDCOLUMNTEMPLATE T ON C.GCUSTOMFIELD = T.GCUSTOMFIELD
INNER JOIN CUSTOMFIELDTABLECOLUMNREF R ON T.CUSTOMFIELDCOLUMNTEMPLATEID = R.CUSTOMFIELDCOLUMNTEMPLATEID
INNER JOIN CUSTOMSAVERTBLCOL_INT X ON R.CUSTOMFIELDTABLECOLUMNREFID = X.CFTABLECOLUMNREFID
WHERE 
	--X.OBJECTID = @PMPERMITID		
	--AND 
	C.SFIELDNAME IN ('COLNUM_BelowGradeLevels')
	AND R.CUSTOMFIELDTABLEID IN ('489e9435-597b-412d-a296-5e8a1f9ffdc5') 
	) X
	PIVOT(MAX(X.XVAL) FOR X.SFIELDNAME IN ([Above Grade Level], [Below Grade Level])
	) P
	WHERE COALESCE([Above Grade Level], [Below Grade Level]) IS NOT NULL
	) 
SELECT P.PMPERMITID, P.PERMITNUMBER, P.ISSUEDATE, P.VALUE TOTALVALUATION, P.SQUAREFEET
	, UPPER(PT.NAME) PERMITTYPE, UPPER(PWC.NAME) TYPEOFAPPLICATION
	, A.CONTACTNAME APPLICANTNAME, A.PHONE APPPHONE, A.CONTACTCOMPANY APPCOMPANY
	, UPPER(AA.AL1) APP_AL1, UPPER(AA.AL2) APP_AL2
	, O.CONTACTNAME OWNERNAME, O.PHONE OWNPHONE, O.CONTACTCOMPANY OWNCOMPANY
	, UPPER(OA.AL1) OWN_AL1, UPPER(OA.AL2) OWN_AL2
	, C.CONTACTNAME CONTRACTORNAME, C.PHONE CONPHONE, C.CONTACTCOMPANY CONCOMPANY
	, UPPER(CA.AL1) CON_AL1, UPPER(CA.AL2) CON_AL2
	, SC.CONTACTNAME SITECONTACTNAME, SC.PHONE SCPHONE, SC.CONTACTCOMPANY SCCOMPANY
	, UPPER(SCA.AL1) SCA_AL1, UPPER(SCA.AL2) SCA_AL2
	, UPPER(RTRIM(LTRIM(COALESCE(MA.POBOX,'') + ' ')
		+ LTRIM(COALESCE(MA.ADDRESSLINE1,'') + ' ') 
		+ LTRIM(COALESCE(MA.PREDIRECTION,'') + ' ') 
		+ LTRIM(COALESCE(MA.ADDRESSLINE2,'') + ' ') 
		+ LTRIM(COALESCE(MA.STREETTYPE,'') + ' ') 
		+ LTRIM(COALESCE(MA.POSTDIRECTION,'') + ' ') 
		+ LTRIM(COALESCE(MA.UNITORSUITE,'') + ' ') 
		+ ' TUC')
	  ) SITEADDRESS_LINE1
	, (CASE WHEN RTRIM(LTRIM(COALESCE(MA.CITY,''))) = '' 
			THEN '' 
			ELSE RTRIM(LTRIM(COALESCE(MA.CITY,''))) + ', ' END)
			+ (LTRIM(COALESCE(MA.[STATE],'') + ' ') 
			+ REPLACE((CASE WHEN LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ','')) > 5 
			THEN LEFT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),5) + '-' + RIGHT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),ABS(LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''))-5)) 
			ELSE COALESCE(MA.POSTALCODE,'') END),'--','-')
		  ) SITEADDRESS_LINE2
	, PAR.PARCELNUMBER
	, NUM_TotalofLevels STORIES
	--, STUFF((SELECT ', ' + CAST((CAST(NS.[Above Grade Level] AS INT) + CAST(NS.[Below Grade Level] AS INT)) AS VARCHAR(200))
	--		FROM NUMSTORIES NS
	--		WHERE NS.PMPERMITID = P.PMPERMITID
	--			AND NULLIF(RTRIM(NS.[Above Grade Level]), '') IS NOT NULL
	--		ORDER BY NS.ROWNUMBER
	--		FOR XML PATH(''), root('MyString'), type
	--		).value('/MyString[1]','varchar(max)'),1,2,''
	--		) STORIES
	, CS1.AUTOTXT_LegalDescrip LEGALDESCRIPTION
	, CS1.AUTOTXT_Twnshp_Sect_Range TRS
	, STUFF((
        SELECT ', ' + [Pick].[SVALUE]
            FROM   CUSTOMSAVERPERMITMANAGEMENTMS MS
			JOIN   CUSTOMFIELDPICKLISTITEM Pick ON Pick.GCUSTOMFIELDPICKLISTITEM = MS.CUSTOMFIELDPICKLISTITEMID
            WHERE  
				--MS.ID = @PMPERMITID
    --            AND 
				MS.CUSTOMFIELDID IN (SELECT C.GCUSTOMFIELD FROM CUSTOMFIELD C WHERE C.SFIELDNAME LIKE 'PCK_OccupancyType')
        ORDER BY Pick.SVALUE
        FOR XML PATH('')
    ), 1, 2, '') OccupancyGroup
	, STUFF((
        SELECT ', ' + [Pick].[SVALUE]
            FROM   CUSTOMSAVERPERMITMANAGEMENTMS MS
			JOIN   CUSTOMFIELDPICKLISTITEM Pick ON Pick.GCUSTOMFIELDPICKLISTITEM = MS.CUSTOMFIELDPICKLISTITEMID
            WHERE  
				--MS.ID = @PMPERMITID
    --            AND 
				MS.CUSTOMFIELDID IN (SELECT C.GCUSTOMFIELD FROM CUSTOMFIELD C WHERE C.SFIELDNAME LIKE 'PCK_ConstructionType')
        ORDER BY Pick.SVALUE
        FOR XML PATH('')
    ), 1, 2, '') ConstructionType
	, COALESCE(NULLIF(UPPER(CS1.TXT_StaffDescription), ''), NULLIF(UPPER(CS1.TXT_ApplicantDescription),'') , NULLIF(UPPER(P.[DESCRIPTION]), ''), '') PROPOSEDWORK
	, (SELECT COUNT(*) 
	   FROM PMPERMITCONDITION PC2 
	   WHERE PC2.PMPERMITID = P.PMPERMITID) AS PERMITCONDITIONCOUNT
	, (SELECT [IMAGE] FROM RPTIMAGELIB WHERE IMAGENAME = 'TucsonPDSDLogo') AS TucsonLogo
	, (SELECT [IMAGE] FROM RPTIMAGELIB WHERE IMAGENAME = 'TucsonLogo') AS TucsonLogoSmall
FROM PMPERMIT P
	LEFT JOIN PMPERMITADDRESS PA ON P.PMPERMITID = PA.PMPERMITID
		AND PA.MAIN = 1
	LEFT JOIN MAILINGADDRESS MA ON PA.MAILINGADDRESSID = MA.MAILINGADDRESSID
	LEFT JOIN PMPERMITPARCEL PPAR ON P.PMPERMITID = PPAR.PMPERMITID
		AND PPAR.MAIN = 1
	LEFT JOIN PARCEL PAR ON PPAR.PARCELID = PAR.PARCELID
	INNER JOIN PMPERMITTYPE PT ON P.PMPERMITTYPEID = PT.PMPERMITTYPEID
	INNER JOIN PMPERMITWORKCLASS PWC ON P.PMPERMITWORKCLASSID = PWC.PMPERMITWORKCLASSID
	LEFT JOIN CONTACTS A ON P.PMPERMITID = A.PMPERMITID
		AND A.CONTACTTYPE = 'Applicant'
		AND A.ROWNBR = 1
	LEFT JOIN CONADD AA ON A.GLOBALENTITYID = AA.GLOBALENTITYID
		AND AA.ROWNBR = 1
	LEFT JOIN CONTACTS O ON P.PMPERMITID = O.PMPERMITID
		AND O.CONTACTTYPE = 'Owner'
		AND O.ROWNBR = 1
	LEFT JOIN CONADD OA ON O.GLOBALENTITYID = OA.GLOBALENTITYID
		AND OA.ROWNBR = 1
	LEFT JOIN CONTACTS C ON P.PMPERMITID = C.PMPERMITID
		AND C.CONTACTTYPE = 'Contractor'
	LEFT JOIN CONADD CA ON C.GLOBALENTITYID = CA.GLOBALENTITYID
		AND CA.ROWNBR = 1
	LEFT JOIN CONTACTS SC ON P.PMPERMITID = SC.PMPERMITID
		AND SC.CONTACTTYPE = 'Site Contact'
	LEFT JOIN CONADD SCA ON SC.GLOBALENTITYID = SCA.GLOBALENTITYID
		AND SCA.ROWNBR = 1
	LEFT JOIN CUSTOMSAVERPERMITMANAGEMENT CS1 ON P.PMPERMITID = CS1.ID
--WHERE P.PMPERMITID = @PMPERMITID


--(1) 
--WHERE P.PERMITNUMBER = 'T22CM07531'
--WHERE P.PMPERMITID = '001BA2D0-7A9A-4EF3-9B13-E4807EDBAA7F'

--(2) 
--WHERE P.PERMITNUMBER = 'TC-RES-0523-05473'
--WHERE P.PMPERMITID = '35b12bf4-2ed4-463d-9a1d-3c9f42a29491'

--(3) No Conditions
--WHERE P.PERMITNUMBER = 'D01-0008'
--WHERE P.PMPERMITID = '000139F6-1F0C-4F2F-9D14-8A9EEBE42EBB'

--(4) Additional Addresses
--WHERE P.PERMITNUMBER = 'TR-ROW-0423-00660'
--WHERE P.PMPERMITID = 'ce3bb320-c0f2-4a1e-b8ae-5e030df0b7a8'




















--END
--GO


