USE [EnerGov_Tucson_Prod]
--GO

--/****** Object:  StoredProcedure [dbo].[rpt_CoT_PDSD_Permit_Addresses]    Script Date: 8/10/2025 1:42:40 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO


--CREATE PROCEDURE [dbo].[rpt_CoT_PDSD_Permit_Addresses]
--@PMPERMITID AS VARCHAR(36)
--AS

--BEGIN

SELECT PMA.PMPERMITID
	, RTRIM(RTRIM(LTRIM(COALESCE(MA.POBOX,'') + ' ')
		+ LTRIM(COALESCE(MA.ADDRESSLINE1,'') + ' ')
		+ LTRIM(COALESCE(MA.PREDIRECTION,'') + ' ') 
		+ LTRIM(COALESCE(MA.ADDRESSLINE2,'') + ' ') 
		+ LTRIM(COALESCE(MA.STREETTYPE,'') + ' ') 
		+ LTRIM(COALESCE(MA.POSTDIRECTION,'') + ' ')
		)
		+ CASE WHEN NULLIF(RTRIM(MA.UNITORSUITE),'') IS NOT NULL
				THEN CHAR(10) + LTRIM(COALESCE(MA.UNITORSUITE,'') + ' ') 
				ELSE ''
			END
		--+ LTRIM(COALESCE(MA.ADDRESSLINE3,''))
		) AL1
		, (CASE WHEN RTRIM(LTRIM(COALESCE(MA.CITY,''))) = '' 
			THEN '' 
			ELSE RTRIM(LTRIM(COALESCE(MA.CITY,''))) + ', ' END)
			+ (LTRIM(COALESCE(MA.[STATE],'') + ' ') 
			+ REPLACE((CASE WHEN LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ','')) > 5 
			THEN LEFT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),5) + '-' + RIGHT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),ABS(LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''))-5)) 
			ELSE COALESCE(MA.POSTALCODE,'') END),'--','-')
		  ) AL2
FROM PMPERMITADDRESS PMA
INNER JOIN MAILINGADDRESS MA ON PMA.MAILINGADDRESSID = MA.MAILINGADDRESSID
WHERE 
--PMA.PMPERMITID = @PMPERMITID AND 
PMA.MAIN <> 1

--END
--GO


