USE [EnerGov_Tucson_Prod]
--GO

--/****** Object:  StoredProcedure [dbo].[rpt_PM_SR_Permit_Fee_Listing]    Script Date: 8/26/2025 3:16:50 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO


--CREATE PROCEDURE [dbo].[rpt_PM_SR_Permit_Fee_Listing]
--	@STARTDATE AS DATETIME,
--	@ENDDATE AS DATETIME,
--	@FILTER AS VARCHAR(150)
--AS

--SET @STARTDATE=DATEADD(DD,DATEDIFF(DD,0,@STARTDATE),0)
--SET @ENDDATE=DATEADD(SS,-1,DATEDIFF(DD,0,@ENDDATE) + 1) 

--BEGIN
DECLARE @TIMEZONEOFFSET AS INT = (SELECT COALESCE((SELECT TOP 1 INTVALUE FROM SETTINGS A WHERE A.[NAME] = 'TIMEZONEOFFSETINHOURS'),0));

SELECT DISTINCT PMPERMIT.PMPERMITID, PMPERMIT.PERMITNUMBER, PMPERMIT.APPLYDATE, PMPERMIT.[EXPIREDATE], PMPERMIT.ISSUEDATE, PMPERMIT.FINALIZEDATE, PMPERMIT.[VALUE], PMPERMIT.SQUAREFEET
	, PMPERMITTYPE.[NAME] AS PERMITTYPE
	, PMPERMITWORKCLASS.[NAME] AS WORKCLASS
	, PMPERMITSTATUS.[NAME] AS [STATUS]
	, CACOMPUTEDFEE.FEENAME
	, CACOMPUTEDFEE.COMPUTEDAMOUNT AS FEEAMOUNT, CACOMPUTEDFEE.AMOUNTPAIDTODATE AS PAIDAMOUNT, CACOMPUTEDFEE.CACOMPUTEDFEEID, CACOMPUTEDFEE.CACOMPUTEDFEEID
	, RTRIM(LTRIM(COALESCE(MA.POBOX,'') + ' ')
		+ COALESCE(MA.ADDRESSLINE1,'') + ' ' 
		+ LTRIM(COALESCE(MA.PREDIRECTION,'') + ' ') 
		+ LTRIM(COALESCE(MA.ADDRESSLINE2,'') + ' ') 
		+ LTRIM(COALESCE(MA.STREETTYPE,'') + ' ') 
		+ LTRIM(COALESCE(MA.POSTDIRECTION,'') + ' ') 
		+ LTRIM(COALESCE(MA.UNITORSUITE,'') + ' ') 
		--+ LTRIM(COALESCE(MA.ADDRESSLINE3,''))
		) ADDRESS_LINE1
	, (CASE WHEN RTRIM(LTRIM(COALESCE(MA.CITY,''))) = '' 
		THEN '' 
		ELSE RTRIM(LTRIM(COALESCE(MA.CITY,''))) + ', ' END)
		+ (LTRIM(COALESCE(MA.[STATE],'') + ' ') 
		+ REPLACE((CASE WHEN LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ','')) > 5 
		THEN LEFT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),5) + '-' + RIGHT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),ABS(LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''))-5)) 
		ELSE COALESCE(MA.POSTALCODE,'') END),'--','-')
		) ADDRESS_LINE2
	, P.PARCELNUMBER
	, STUFF((
		SELECT '||' 
			+ CASE WHEN GE.ISCONTACT = 1 
				THEN GE.FIRSTNAME
					+ CASE WHEN ISNULL(GE.MIDDLENAME,'') = '' 
						THEN '' 
						ELSE ' ' + LEFT(GE.MIDDLENAME,1)  
						END 
					+ ' ' + GE.LASTNAME 
				ELSE GE.GLOBALENTITYNAME 
			END BILLINGCONTACT
		FROM PMPERMITCONTACT PMC
		INNER JOIN GLOBALENTITY GE ON GE.GLOBALENTITYID = PMC.GLOBALENTITYID
		WHERE PMC.PMPERMITID = PMPERMIT.PMPERMITID AND PMC.ISBILLING = 1
		FOR XML PATH(''), root('MyString'), type).value('/MyString[1]','varchar(max)'),1,2,''
	  ) AS 'BILLINGCONTACT'
	, @TIMEZONEOFFSET TIMEZONEOFFSET
	--, (SELECT R.[IMAGE] FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') LOGO
	, (SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO
	, (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name
	, (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
FROM PMPERMIT
INNER JOIN PMPERMITTYPE ON PMPERMIT.PMPERMITTYPEID = PMPERMITTYPE.PMPERMITTYPEID 
INNER JOIN PMPERMITWORKCLASS ON PMPERMIT.PMPERMITWORKCLASSID = PMPERMITWORKCLASS.PMPERMITWORKCLASSID 
INNER JOIN PMPERMITFEE ON PMPERMIT.PMPERMITID = PMPERMITFEE.PMPERMITID 
INNER JOIN CACOMPUTEDFEE ON PMPERMITFEE.CACOMPUTEDFEEID = CACOMPUTEDFEE.CACOMPUTEDFEEID 
INNER JOIN PMPERMITSTATUS ON PMPERMIT.PMPERMITSTATUSID = PMPERMITSTATUS.PMPERMITSTATUSID 
LEFT JOIN PMPERMITCONTACT PMC ON PMPERMIT.PMPERMITID = PMC.PMPERMITID
LEFT JOIN PMPERMITADDRESS PA ON PMPERMIT.PMPERMITID = PA.PMPERMITID
	AND PA.MAIN = 1
LEFT JOIN MAILINGADDRESS MA ON PA.MAILINGADDRESSID = MA.MAILINGADDRESSID
LEFT JOIN PMPERMITPARCEL PMP ON PMPERMIT.PMPERMITID = PMP.PMPERMITID 
	AND PMP.MAIN = 1
LEFT JOIN PARCEL P ON P.PARCELID = PMP.PARCELID
WHERE CACOMPUTEDFEE.CASTATUSID NOT IN (5,9,10) --VOID, DELETED
	--AND CASE @FILTER 
	--		WHEN 'EXPIRATION DATE' THEN PMPERMIT.[EXPIREDATE]
	--		WHEN 'APPLIED DATE' THEN PMPERMIT.APPLYDATE
	--		WHEN 'FINALED DATE' THEN PMPERMIT.FINALIZEDATE
	--		WHEN 'ISSUED DATE' THEN PMPERMIT.ISSUEDATE 
	--	END BETWEEN @STARTDATE AND @ENDDATE

--END
--GO


