USE [EnerGov_Tucson_Prod]
--GO

--/****** Object:  StoredProcedure [dbo].[rpt_PM_SR_Permit_and_Plan_Reviews_Listing]    Script Date: 8/26/2025 2:16:20 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO


--CREATE PROCEDURE [dbo].[rpt_PM_SR_Permit_and_Plan_Reviews_Listing]
--	@STARTDATE AS DATETIME,
--	@ENDDATE AS DATETIME
--AS

--SET @STARTDATE=DATEADD(DD,DATEDIFF(DD,0,@STARTDATE),0)
--SET @ENDDATE=DATEADD(SS,-1,DATEDIFF(DD,0,@ENDDATE) + 1) 

--BEGIN
DECLARE @TIMEZONEOFFSET AS INT = (SELECT COALESCE((SELECT TOP 1 INTVALUE FROM SETTINGS A WHERE A.[NAME] = 'TIMEZONEOFFSETINHOURS'),0));

SELECT 'PM' AS PMorPL
	, P.PERMITNUMBER AS PermitNumber
	, ST.TYPENAME AS SubmittalType
	, IT.[NAME] AS ReviewType
	, D.[NAME] AS Department
	, I.COMMENTS AS ReviewComments, I.ASSIGNEDDATE AS AssignedDate, I.DUEDATE AS DueDate, I.COMPLETEDATE, I.COMPLETED
	, IRS.[NAME] AS ReviewStatus
	, WFAS.VERSIONNUMBER PRIORITYORDER
	, CASE I.NOTREQUIRED WHEN NULL THEN 1 
		WHEN 1 THEN 0 
		ELSE 1 
	  END NOTREQUIRED
	, U.FNAME + ' ' + U.LNAME AS AssignedUser
	, MA.ADDRESSLINE1 AS AddressLine1, MA.ADDRESSLINE2 AS AddressLine2, MA.ADDRESSLINE3 AS AddressLine3, MA.PREDIRECTION AS PreDirection
	, MA.POSTDIRECTION AS PostDirection, MA.STREETTYPE AS StreetType, MA.UNITORSUITE AS UnitOrSuite, MA.CITY AS City, MA.[STATE] AS [State]
	, MA.POSTALCODE AS PostalCode
	, @TIMEZONEOFFSET TIMEZONEOFFSET
	, (SELECT R.[IMAGE] FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') LOGO
	, (SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO
	, (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name
	, (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
FROM PMPERMIT P
INNER JOIN PLSUBMITTAL S ON S.PMPERMITID = P.PMPERMITID 
INNER JOIN PLITEMREVIEW I ON S.PLSUBMITTALID = I.PLSUBMITTALID 
INNER JOIN PLITEMREVIEWTYPE IT ON I.PLITEMREVIEWTYPEID = IT.PLITEMREVIEWTYPEID 
INNER JOIN DEPARTMENT D ON IT.DEPARTMENTID = D.DEPARTMENTID 
INNER JOIN USERS U ON I.ASSIGNEDUSERID = U.SUSERGUID 
INNER JOIN PLSUBMITTALTYPE ST ON S.PLSUBMITTALTYPEID = ST.PLSUBMITTALTYPEID 
INNER JOIN PLITEMREVIEWSTATUS IRS ON I.PLITEMREVIEWSTATUSID = IRS.PLITEMREVIEWSTATUSID
LEFT JOIN PMPERMITADDRESS PA ON P.PMPERMITID = PA.PMPERMITID
	AND PA.MAIN = 1
LEFT JOIN MAILINGADDRESS MA ON PA.MAILINGADDRESSID = MA.MAILINGADDRESSID
LEFT JOIN PMPERMITWFACTIONSTEP WFAS ON S.PMPERMITWFACTIONSTEPID = WFAS.PMPERMITWFACTIONSTEPID
--WHERE I.DUEDATE BETWEEN @STARTDATE AND @ENDDATE

UNION

SELECT 'PL' PMorPL
	, P.PLANNUMBER AS PlanNumber
	, ST.TYPENAME AS SubmittalType
	, IT.[NAME] AS ReviewType
	, D.[NAME] AS Department
	, I.COMMENTS AS ReviewComments, I.ASSIGNEDDATE AS AssignedDate, I.DUEDATE AS DueDate, I.COMPLETEDATE, I.COMPLETED
	, IRS.[NAME] AS ReviewStatus
	, WFAS.VERSIONNUMBER PRIORITYORDER
	, CASE I.NOTREQUIRED WHEN NULL THEN 1 
		WHEN 1 THEN 0 
		ELSE 1 
	  END NOTREQUIRED
	, U.FNAME + ' ' + U.LNAME AS AssignedUser
	, MA.ADDRESSLINE1, MA.ADDRESSLINE2, MA.ADDRESSLINE3, MA.PREDIRECTION, MA.POSTDIRECTION, MA.STREETTYPE
	, MA.UNITORSUITE, MA.CITY, MA.[STATE], MA.POSTALCODE
	, @TIMEZONEOFFSET TIMEZONEOFFSET
	, (SELECT R.[IMAGE] FROM RPTIMAGELIB R	WHERE R.IMAGENAME = 'Municipality_Logo') LOGO
	, (SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R	WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO
	, (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name
	, (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
FROM PLPLAN AS P
INNER JOIN PLPLANWFSTEP WFS ON P.PLPLANID = WFS.PLPLANID 
INNER JOIN PLPLANWFACTIONSTEP WFAS ON WFS.PLPLANWFSTEPID = WFAS.PLPLANWFSTEPID 
INNER JOIN PLSUBMITTAL S ON WFAS.PLPLANWFACTIONSTEPID = S.PLPLANWFACTIONSTEPID 
INNER JOIN PLITEMREVIEW I ON S.PLSUBMITTALID = I.PLSUBMITTALID 
INNER JOIN PLITEMREVIEWTYPE IT ON I.PLITEMREVIEWTYPEID = IT.PLITEMREVIEWTYPEID 
INNER JOIN DEPARTMENT D ON IT.DEPARTMENTID = D.DEPARTMENTID 
INNER JOIN USERS U ON I.ASSIGNEDUSERID = U.SUSERGUID 
INNER JOIN PLSUBMITTALTYPE ST ON S.PLSUBMITTALTYPEID = ST.PLSUBMITTALTYPEID 
INNER JOIN PLITEMREVIEWSTATUS IRS ON I.PLITEMREVIEWSTATUSID = IRS.PLITEMREVIEWSTATUSID
LEFT JOIN PLPLANADDRESS PA ON P.PLPLANID = PA.PLPLANID
	AND PA.MAIN = 1
LEFT JOIN MAILINGADDRESS MA ON PA.MAILINGADDRESSID = MA.MAILINGADDRESSID
--WHERE I.DUEDATE BETWEEN @STARTDATE AND @ENDDATE

--END
--GO


