IF OBJECT_ID('tempdb.dbo.#FILTER') IS NOT NULL
	DROP TABLE #FILTER;
SELECT P.PMPERMITID, P.PERMITNUMBER
	, PT.[NAME] PERMITTYPE, WC.[NAME] WORKCLASS, PS.[NAME] PERMITSTATUS
	, P.APPLYDATE, P.ISSUEDATE
	, P.[DESCRIPTION]
	, PI_CensusCode.SVALUE CENSUSCODE
	, CS.NumberOfUnits
	, CEILING(P.[VALUE]/1000) * 1000 ActualValuation
	, P.[VALUE]
INTO #FILTER
FROM PMPERMIT P
INNER JOIN PMPERMITTYPE PT ON P.PMPERMITTYPEID = PT.PMPERMITTYPEID
	AND PT.[NAME] NOT IN ( 'Building - Master Plan' )
INNER JOIN PMPERMITWORKCLASS WC ON P.PMPERMITWORKCLASSID = WC.PMPERMITWORKCLASSID
INNER JOIN PMPERMITSTATUS PS ON P.PMPERMITSTATUSID = PS.PMPERMITSTATUSID
LEFT JOIN CUSTOMSAVERPERMITMANAGEMENT CS ON P.PMPERMITID = CS.ID
LEFT JOIN CUSTOMFIELDPICKLISTITEM PI_CensusCode ON CS.DepartmentofCommerceCodeCensusCode = PI_CensusCode.GCUSTOMFIELDPICKLISTITEM
	AND PI_CensusCode.SVALUE <> '000 - Not applicable'
--WHERE P.ISSUEDATE BETWEEN @STARTDATE AND @ENDDATE

;WITH PERMITCOUNTS AS (
SELECT F.CENSUSCODE, F.PERMITNUMBER

--, SUM(CAST(F.NumberOfUnits AS INT)) NumberofUnits
--,SUM(TRY_CAST(F.NumberOfUnits AS INT)) AS NumberOfUnits
,SUM(TRY_CAST(
			CASE 
				WHEN F.NumberOfUnits LIKE '[0-9]%'
				THEN SUBSTRING(F.NumberOfUnits, 1, PATINDEX('%[^0-9]%', F.NumberOfUnits + ' ') - 1)
				ELSE NULL
			END AS INT)
	) AS NumberofUnits


, COUNT(F.PMPERMITID) NumberofPermits
	, SUM(F.ActualValuation) ConstructionValuation
FROM #FILTER F
GROUP BY F.CENSUSCODE, F.PERMITNUMBER
)

SELECT CASE WHEN TI.SVALUE LIKE '1%' THEN 'New Residential Building'
			WHEN TI.SVALUE LIKE '2%' OR TI.SVALUE LIKE '32%' OR TI.SVALUE LIKE '31%' THEN 'New Non-Residential Buildings'
			WHEN TI.SVALUE LIKE '4%' THEN 'Additions, Alterations, and Conversions of Existing Structures'
			WHEN TI.SVALUE LIKE '340%' OR TI.SVALUE LIKE '50%' THEN 'Energy Permits'
				END GROUPNAME
	, TI.SVALUE CENSUSCODE, COALESCE(PC.NumberofUnits, 0) NumberofUnits
	,PC.PERMITNUMBER
	, COALESCE(PC.NumberofPermits, 0) NumerofPermits
	, COALESCE(PC.ConstructionValuation, $0) ConstructionValuation
	, (SELECT R.[IMAGE] FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'RanchoLogoLarge') RCLOGO
	, (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Building Dept. Address') BUILDINGANDSAFETYHEADER
FROM CUSTOMFIELDLAYOUT L
LEFT JOIN CUSTOMFIELDOBJECT OBJ ON L.GCUSTOMFIELDLAYOUTS = OBJ.FKGCUSTOMFIELDLAYOUT
LEFT JOIN CUSTOMFIELD C ON OBJ.GCUSTOMFIELD = C.GCUSTOMFIELD
LEFT JOIN CUSTOMFIELDTEMPLATE T ON C.FKGCUSTOMFIELDTEMPLATE = T.GCUSTOMFIELDTEMPLATE
LEFT JOIN CUSTOMFIELDTEMPLATEITEM TI ON T.GCUSTOMFIELDTEMPLATE = TI.FKGCUSTOMFIELDTEMPLATE
	AND TI.SVALUE <> '000 - Not applicable'
LEFT JOIN PERMITCOUNTS PC ON TI.SVALUE = PC.CENSUSCODE
WHERE L.SNAME LIKE 'Building - Commercial'
	AND C.SFIELDNAME LIKE 'DepartmentofCommerceCodeCensusCode'
	AND PC.PERMITNUMBER = '590696' -- 150
	--AND PC.PERMITNUMBER = '591651'  -- 2
	--OR PC.PERMITNUMBER = '580963'  -- 0
	--AND PC.NumberOfUnits IS NOT NULL 
	--AND PC.NumberOfUnits != '0'
	--AND PC.NumberOfUnits != '1'
ORDER BY CASE WHEN TI.SVALUE LIKE '1%' THEN 1
			WHEN TI.SVALUE LIKE '2%' OR TI.SVALUE LIKE '32%' OR TI.SVALUE LIKE '31%' THEN 3
			WHEN TI.SVALUE LIKE '4%' THEN 5
			WHEN TI.SVALUE LIKE '340%' OR TI.SVALUE LIKE '50%' THEN 7
				ELSE 10
				END, TI.SVALUE
