USE [EnerGov_Tucson_Prod]
--GO

--/****** Object:  StoredProcedure [dbo].[rpt_CoT_PM_SR_ReviewCoordinatorReport]    Script Date: 8/15/2025 4:17:58 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO


--CREATE PROCEDURE [dbo].[rpt_CoT_PM_SR_ReviewCoordinatorReport]

--AS
--BEGIN

DECLARE @TEAMTABLE AS BIT = CASE WHEN EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS ISC WHERE ISC.TABLE_NAME = 'SYSTEMTASK' AND ISC.COLUMN_NAME = 'TEAMASSIGNEDTO')
		THEN 1
		ELSE 0
	  END
	--, @SHOWLOGO AS BIT = (SELECT CASE WHEN R.[IMAGE] IS NULL THEN 0 ELSE 1 END FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo')
	--, @Municipality_Name AS VARCHAR(4000) = (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Name')
	--, @Municipality_Page_Footer AS VARCHAR(4000) = (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Page_Footer')
	--, @TODAY AS DATETIME = GETDATE()
;

IF OBJECT_ID('tempdb.dbo.#FILTER') IS NOT NULL
	DROP TABLE #FILTER;
SELECT ST.SYSTEMTASKID
INTO #FILTER
FROM SYSTEMTASK ST
WHERE ST.COMPLETEDDATE IS NULL
;CREATE INDEX TEMP1 ON #FILTER(SYSTEMTASKID)
;

IF OBJECT_ID('tempdb.dbo.#ASSIGNEDTO') IS NOT NULL
	DROP TABLE #ASSIGNEDTO;
CREATE TABLE #ASSIGNEDTO (SYSTEMTASKID CHAR(36), ASSIGNEDTO NVARCHAR(300), DEPARTMENT NVARCHAR(300))
;CREATE INDEX TEMP1 ON #ASSIGNEDTO(SYSTEMTASKID)
;

DECLARE @SQL AS VARCHAR(MAX);
IF @TEAMTABLE = 1
BEGIN
	SET @SQL = 
		'
			SELECT F.SYSTEMTASKID
				, COALESCE(NULLIF(RTRIM(U.FNAME + '' '' + U.LNAME),''''),T.[NAME]) ASSIGNEDTO
				, COALESCE(D.[NAME], ''*N/A'') DEPARTMENT
			FROM #FILTER F
			INNER JOIN SYSTEMTASK ST ON F.SYSTEMTASKID = ST.SYSTEMTASKID
			LEFT JOIN USERS U ON ST.ASSIGNEDTO = U.SUSERGUID
			LEFT JOIN TEAM T ON ST.TEAMASSIGNEDTO = T.TEAMID
			LEFT JOIN USERDEPARTMENT UD ON U.SUSERGUID = UD.SUSERGUID
			LEFT JOIN DEPARTMENT D ON UD.DEPARTMENTID = D.DEPARTMENTID
		'
END
ELSE
BEGIN
	SET @SQL = 
		'
			SELECT F.SYSTEMTASKID
				, U.FNAME + '' '' + U.LNAME ASSIGNEDTO
				, COALESCE(D.[NAME], ''*N/A'') DEPARTMENT
			FROM #FILTER F
			INNER JOIN SYSTEMTASK ST ON F.SYSTEMTASKID = ST.SYSTEMTASKID
			LEFT JOIN USERS U ON ST.ASSIGNEDTO = U.SUSERGUID
			LEFT JOIN USERDEPARTMENT UD ON U.SUSERGUID = UD.SUSERGUID
			LEFT JOIN DEPARTMENT D ON UD.DEPARTMENTID = D.DEPARTMENTID
		'
END

INSERT INTO #ASSIGNEDTO
	EXECUTE(@SQL);

SELECT X.DEPARTMENT, X.ASSIGNEDTO, X.DUEDATE, X.RECORDNUMBER, X.PROJECTNAME, X.TASKTYPE, X.AL1
	, X.COMPLETEDDATE, X.CREATEDON
	, DATEDIFF(DAY,X.CREATEDON,COALESCE(X.COMPLETEDDATE,GETDATE())) DAYSOPEN
	, (SELECT CASE WHEN R.[IMAGE] IS NULL THEN 0 ELSE 1 END FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO
	, (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name
	, (SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
	
FROM (
	/* FILES TASK PLAN */
	SELECT ST.SYSTEMTASKID, ST.UNIQUERECORDID, ST.DUEDATE, ST.COMPLETEDDATE, ST.CREATEDON
		, STT.[NAME] TASKTYPE
		, AST.ASSIGNEDTO
		, PL.PLANNUMBER RECORDNUMBER
		, PR.[NAME] PROJECTNAME
		, RTRIM(LTRIM(COALESCE(MA.POBOX,'') + ' ')
			+ COALESCE(MA.ADDRESSLINE1,'') + ' ' 
			+ LTRIM(COALESCE(MA.PREDIRECTION,'') + ' ') 
			+ LTRIM(COALESCE(MA.ADDRESSLINE2,'') + ' ') 
			+ LTRIM(COALESCE(MA.STREETTYPE,'') + ' ') 
			+ LTRIM(COALESCE(MA.POSTDIRECTION,'') + ' ') 
			+ LTRIM(COALESCE(MA.UNITORSUITE,'') + ' ') 
			--+ LTRIM(COALESCE(MA.ADDRESSLINE3,''))
		  ) AL1
		, AST.DEPARTMENT
	FROM #FILTER F
	INNER JOIN SYSTEMTASK ST ON F.SYSTEMTASKID = ST.SYSTEMTASKID
	INNER JOIN SYSTEMTASKTYPE STT ON ST.SYSTEMTASKTYPEID = STT.SYSTEMTASKTYPEID
	LEFT JOIN #ASSIGNEDTO AST ON ST.SYSTEMTASKID = AST.SYSTEMTASKID
	INNER JOIN PLPLAN PL ON ST.UNIQUERECORDID = PL.PLPLANID
	LEFT JOIN PRPROJECTPLAN PPL ON PL.PLPLANID = PPL.PLPLANID
	LEFT JOIN PRPROJECT PR ON PPL.PRPROJECTID = PR.PRPROJECTID
	LEFT JOIN PLPLANADDRESS PA ON PL.PLPLANID = PA.PLPLANID
		AND PA.MAIN = 1
	LEFT JOIN MAILINGADDRESS MA ON PA.MAILINGADDRESSID = MA.MAILINGADDRESSID
	
	UNION ALL
	/* FILES TASK PERMIT */
	SELECT ST.SYSTEMTASKID, ST.UNIQUERECORDID, ST.DUEDATE, ST.COMPLETEDDATE, ST.CREATEDON
		, STT.[NAME] TASKTYPE
		, AST.ASSIGNEDTO
		, PM.PERMITNUMBER RECORDNUMBER
		, PR.[NAME] PROJECTNAME
		, RTRIM(LTRIM(COALESCE(MA.POBOX,'') + ' ')
			+ COALESCE(MA.ADDRESSLINE1,'') + ' ' 
			+ LTRIM(COALESCE(MA.PREDIRECTION,'') + ' ') 
			+ LTRIM(COALESCE(MA.ADDRESSLINE2,'') + ' ') 
			+ LTRIM(COALESCE(MA.STREETTYPE,'') + ' ') 
			+ LTRIM(COALESCE(MA.POSTDIRECTION,'') + ' ') 
			+ LTRIM(COALESCE(MA.UNITORSUITE,'') + ' ') 
			--+ LTRIM(COALESCE(MA.ADDRESSLINE3,''))
		  ) AL1
		, AST.DEPARTMENT
	FROM #FILTER F
	INNER JOIN SYSTEMTASK ST ON F.SYSTEMTASKID = ST.SYSTEMTASKID
	INNER JOIN SYSTEMTASKTYPE STT ON ST.SYSTEMTASKTYPEID = STT.SYSTEMTASKTYPEID
	LEFT JOIN #ASSIGNEDTO AST ON ST.SYSTEMTASKID = AST.SYSTEMTASKID
	INNER JOIN PMPERMIT PM ON ST.UNIQUERECORDID = PM.PMPERMITID
	LEFT JOIN PRPROJECTPERMIT PPM ON PM.PMPERMITID = PPM.PMPERMITID
	LEFT JOIN PRPROJECT PR ON PPM.PRPROJECTID = PR.PRPROJECTID
	LEFT JOIN PMPERMITADDRESS PA ON PM.PMPERMITID = PA.PMPERMITID
		AND PA.MAIN = 1
	LEFT JOIN MAILINGADDRESS MA ON PA.MAILINGADDRESSID = MA.MAILINGADDRESSID
	
	UNION ALL
	/* SUBMITTALS TASK */
	SELECT ST.SYSTEMTASKID, ST.UNIQUERECORDID, ST.DUEDATE, ST.COMPLETEDDATE, ST.CREATEDON
		, STT.[NAME] TASKTYPE
		, AST.ASSIGNEDTO
		, COALESCE(PM.PERMITNUMBER, PL.PLANNUMBER) RECORDNUMBER
		, PR.[NAME] PROJECTNAME
		, RTRIM(LTRIM(COALESCE(MA.POBOX,'') + ' ')
			+ COALESCE(MA.ADDRESSLINE1,'') + ' ' 
			+ LTRIM(COALESCE(MA.PREDIRECTION,'') + ' ') 
			+ LTRIM(COALESCE(MA.ADDRESSLINE2,'') + ' ') 
			+ LTRIM(COALESCE(MA.STREETTYPE,'') + ' ') 
			+ LTRIM(COALESCE(MA.POSTDIRECTION,'') + ' ') 
			+ LTRIM(COALESCE(MA.UNITORSUITE,'') + ' ') 
			--+ LTRIM(COALESCE(MA.ADDRESSLINE3,''))
		  ) AL1
		, AST.DEPARTMENT
	FROM #FILTER F
	INNER JOIN SYSTEMTASK ST ON F.SYSTEMTASKID = ST.SYSTEMTASKID
	INNER JOIN SYSTEMTASKTYPE STT ON ST.SYSTEMTASKTYPEID = STT.SYSTEMTASKTYPEID
	LEFT JOIN #ASSIGNEDTO AST ON ST.SYSTEMTASKID = AST.SYSTEMTASKID
	INNER JOIN PLSUBMITTAL S ON ST.UNIQUERECORDID = S.PLSUBMITTALID
	INNER JOIN PLSUBMITTALTYPE STYPE ON S.PLSUBMITTALTYPEID = STYPE.PLSUBMITTALTYPEID
	LEFT JOIN PMPERMIT PM ON S.PMPERMITID = PM.PMPERMITID
	LEFT JOIN PRPROJECTPERMIT PPM ON PM.PMPERMITID = PPM.PMPERMITID
	LEFT JOIN PMPERMITADDRESS PMA ON PM.PMPERMITID = PMA.PMPERMITID
		AND PMA.MAIN = 1
	LEFT JOIN PLPLAN PL ON S.PLPLANID = PL.PLPLANID
	LEFT JOIN PRPROJECTPLAN PPL ON PL.PLPLANID = PPL.PLPLANID
	LEFT JOIN PLPLANADDRESS PLA ON PL.PLPLANID = PLA.PLPLANID
		AND PLA.MAIN = 1
	LEFT JOIN PRPROJECT PR ON COALESCE(PPM.PRPROJECTID, PPL.PRPROJECTID) = PR.PRPROJECTID
	LEFT JOIN MAILINGADDRESS MA ON COALESCE(PMA.MAILINGADDRESSID, PLA.MAILINGADDRESSID) = MA.MAILINGADDRESSID
) X
ORDER BY X.ASSIGNEDTO ASC
--END
--GO


