USE [EnerGov_Tucson_Prod]
--GO

--/****** Object:  StoredProcedure [dbo].[rpt_PL_ConsolidatedMaterPlanApproval]    Script Date: 8/14/2025 8:34:39 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO



--CREATE PROCEDURE [dbo].[rpt_PL_ConsolidatedMaterPlanApproval]
--	@PLPLANID AS CHAR(36)
--AS

--BEGIN
--DECLARE @PLPLANID AS CHAR(36) = '782a496f-6e0f-4319-a203-f185d7de10d4';
;WITH 
	CONTACTS AS (
		SELECT PC.PLPLANID, PC.GLOBALENTITYID
			, LMCT.[NAME] CONTACTTYPE
			, GE.FIRSTNAME + ' ' + GE.LASTNAME CONTACTNAME
			, GE.GLOBALENTITYNAME COMPANYNAME
		, COALESCE(NULLIF(RTRIM(GE.BUSINESSPHONE),''), NULLIF(RTRIM(GE.MOBILEPHONE),''), NULLIF(RTRIM(GE.HOMEPHONE),''), NULLIF(RTRIM(GE.OTHERPHONE),'')) PHONE
		, GE.EMAIL
		, ROW_NUMBER () OVER (
			PARTITION BY PC.PLPLANID, LMCT.[NAME]
			ORDER BY PC.ISBILLING DESC, PC.GLOBALENTITYID
		  ) ROWNBR
		FROM PLPLANCONTACT PC
			INNER JOIN GLOBALENTITY GE ON PC.GLOBALENTITYID = GE.GLOBALENTITYID
			INNER JOIN LANDMANAGEMENTCONTACTTYPE LMCT ON PC.LANDMANAGEMENTCONTACTTYPEID = LMCT.LANDMANAGEMENTCONTACTTYPEID
		--WHERE PC.PLPLANID = @PLPLANID
	), CONADD AS (
		SELECT C.GLOBALENTITYID
		, RTRIM(RTRIM(LTRIM(COALESCE(MA.POBOX,'') + ' ')
			+ LTRIM(COALESCE(MA.ADDRESSLINE1,'') + ' ')
			+ LTRIM(COALESCE(MA.PREDIRECTION,'') + ' ') 
			+ LTRIM(COALESCE(MA.ADDRESSLINE2,'') + ' ') 
			+ LTRIM(COALESCE(MA.STREETTYPE,'') + ' ') 
			+ LTRIM(COALESCE(MA.POSTDIRECTION,'') + ' ')
		  )
			+ CASE WHEN NULLIF(RTRIM(MA.UNITORSUITE),'') IS NOT NULL
					THEN CHAR(10) + LTRIM(COALESCE(MA.UNITORSUITE,'') + ' ') 
					ELSE ''
			  END
			--+ LTRIM(COALESCE(MA.ADDRESSLINE3,''))
		  ) AL1
		, (CASE WHEN RTRIM(LTRIM(COALESCE(MA.CITY,''))) = '' 
			THEN '' 
			ELSE RTRIM(LTRIM(COALESCE(MA.CITY,''))) + ', ' END)
			+ (LTRIM(COALESCE(MA.[STATE],'') + ' ') 
			+ REPLACE((CASE WHEN LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ','')) > 5 
			THEN LEFT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),5) + '-' + RIGHT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),ABS(LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''))-5)) 
			ELSE COALESCE(MA.POSTALCODE,'') END),'--','-')
		  ) AL2
		  , ROW_NUMBER () OVER (
			PARTITION BY C.GLOBALENTITYID
			ORDER BY GEMA.MAIN DESC, MA.MAILINGADDRESSID
		  ) ROWNBR
	FROM CONTACTS C
	INNER JOIN GLOBALENTITYMAILINGADDRESS GEMA ON C.GLOBALENTITYID = GEMA.GLOBALENTITYID
	INNER JOIN MAILINGADDRESS MA ON GEMA.MAILINGADDRESSID = MA.MAILINGADDRESSID
	), REVIEWCONDITIONS AS (
		SELECT PC.PLANID PLPLANID, C.[DESCRIPTION], C.[ORDER]
		FROM PLPLANCONDITION PC
			LEFT JOIN CONDITION C ON PC.CONDITIONID = C.CONDITIONID
		--WHERE PC.PLANID = @PLPLANID
		 
	)
SELECT P.PLPLANID
	, P.PLANNUMBER, P.DESCRIPTION PROJECTNAME
	, E.CONTACTNAME, E.COMPANYNAME
	, EA.AL1 ENGINEERADDRESS_LINE1, EA.AL2 ENGINEERADDRESS_LINE2
	, U.FNAME, U.LNAME, U.TITLE, U.PHONE
	, RC.[DESCRIPTION] CONDITIONDESCRIPTION
	, RC.[ORDER] CONDITIONORDER
	, (SELECT [IMAGE] FROM RPTIMAGELIB WHERE IMAGENAME = 'TucsonLogo') AS TucsonLogo
	 , (SELECT [IMAGE] FROM RPTIMAGELIB WHERE IMAGENAME = 'TucsonWaterLogo') AS TucsonWaterLogo
FROM PLPLAN P
	LEFT JOIN CONTACTS E ON P.PLPLANID = E.PLPLANID
		AND E.CONTACTTYPE = 'Engineer' --!Change to Engineer
	LEFT JOIN CONADD EA ON E.GLOBALENTITYID = EA.GLOBALENTITYID
		AND EA.ROWNBR = 1
	LEFT JOIN USERS U ON P.ASSIGNEDTO = U.SUSERGUID
	LEFT JOIN REVIEWCONDITIONS RC ON P.PLPLANID = RC.PLPLANID
--WHERE P.PLPLANID = @PLPLANID

--WHERE 
--P.DESCRIPTION IS NOT NULL
--AND E.CONTACTNAME IS NOT NULL 
--AND E.COMPANYNAME IS NOT NULL
--AND EA.AL1 IS NOT NULL
--AND EA.AL2 IS NOT NULL
--AND U.FNAME IS NOT NULL
--AND U.LNAME IS NOT NULL
--AND U.TITLE IS NOT NULL
--AND U.PHONE IS NOT NULL
--RC.DESCRIPTION IS NOT NULL
--ORDER BY P.PLPLANID
--AND RC.[ORDER] IS NOT NULL


--(1) Complete Record
--WHERE P.PLPLANID = '5CCC2DDA-038D-448A-866E-74ECE6882D31'
--WHERE P.PLANNUMBER = 'T22PI00009'

--(2) Title
--WHERE P.PLPLANID = '8BE09124-862F-461A-B27D-2890BB67B8E2'
--WHERE P.PLANNUMBER = 'T22PI00012'

--(3) Phone
WHERE P.PLPLANID = '88e8944d-b0a2-469e-b478-8f9b9dbe90f8'
--WHERE P.PLANNUMBER = 'TW-WCP-0923-00105'

--(4) Multiple Condition Description 
--WHERE P.PLPLANID = '017DAAB9-053F-4209-8E03-77C95A10C45E'
--WHERE P.PLANNUMBER = 'T05BA00015'

--(5) NULLS
--WHERE P.PLPLANID = '0004df1d-f51c-405f-b0e0-e736773d0c89'
--WHERE P.PLANNUMBER = 'TW-WAV-0823-00222'


--No records have Condition Order
















--END
--GO


