USE [EnerGov_Tucson_Prod]
--GO

--/****** Object:  StoredProcedure [dbo].[rpt_CoT_PL_TW_ConstructionAgreement]    Script Date: 8/13/2025 8:52:43 AM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO


----Create Procedure
--CREATE PROCEDURE [dbo].[rpt_CoT_PL_TW_ConstructionAgreement]
--@PLPLANID AS CHAR(36) --Declare Parameter
--AS

--BEGIN

/*
Columns needed from tables based on the sample provided

MAIN Query
	PLPLAN Table
		Plan Number
	CUSTOMSAVERPLANMANAGEMENT
		TXT_ProjectNameTitle
		AUTOTXT_Twnshp_Sect_Range

CTE Subquery
	PLPLANCONTACT -> GLOBALENTITY TABLES
		GLOBALENTITYNAME
		ADDRESS LINE 1
		ADDRESS LINE 2
*/
--DECLARE @PLPLANID AS CHAR(36) = '88e8944d-b0a2-469e-b478-8f9b9dbe90f8'; --For Testing

--Contacts CTE
;WITH 
	CONTACTS AS (
		SELECT PC.PLPLANID, PC.GLOBALENTITYID
			, LMCT.[NAME] CONTACTTYPE
			, GE.FIRSTNAME + ' ' + GE.LASTNAME CONTACTNAME
			, GE.GLOBALENTITYNAME COMPANYNAME
		, COALESCE(NULLIF(RTRIM(GE.BUSINESSPHONE),''), NULLIF(RTRIM(GE.MOBILEPHONE),''), NULLIF(RTRIM(GE.HOMEPHONE),''), NULLIF(RTRIM(GE.OTHERPHONE),'')) PHONE
		, GE.EMAIL
		, ROW_NUMBER () OVER (
			PARTITION BY LMCT.[NAME]
			ORDER BY PC.ISBILLING DESC, PC.GLOBALENTITYID
		  ) ROWNBR
		FROM PLPLANCONTACT PC
			INNER JOIN GLOBALENTITY GE ON PC.GLOBALENTITYID = GE.GLOBALENTITYID
			INNER JOIN LANDMANAGEMENTCONTACTTYPE LMCT ON PC.LANDMANAGEMENTCONTACTTYPEID = LMCT.LANDMANAGEMENTCONTACTTYPEID
		--WHERE PC.PLPLANID = @PLPLANID
--Contact Address CTE
	), CONADD AS (
		SELECT C.GLOBALENTITYID
		, RTRIM(RTRIM(LTRIM(COALESCE(MA.POBOX,'') + ' ')
			+ LTRIM(COALESCE(MA.ADDRESSLINE1,'') + ' ')
			+ LTRIM(COALESCE(MA.PREDIRECTION,'') + ' ') 
			+ LTRIM(COALESCE(MA.ADDRESSLINE2,'') + ' ') 
			+ LTRIM(COALESCE(MA.STREETTYPE,'') + ' ') 
			+ LTRIM(COALESCE(MA.POSTDIRECTION,'') + ' ')
		  )
			+ CASE WHEN NULLIF(RTRIM(MA.UNITORSUITE),'') IS NOT NULL
					THEN CHAR(10) + LTRIM(COALESCE(MA.UNITORSUITE,'') + ' ') 
					ELSE ''
			  END
		  ) AL1
		, (CASE WHEN RTRIM(LTRIM(COALESCE(MA.CITY,''))) = '' 
			THEN '' 
			ELSE RTRIM(LTRIM(COALESCE(MA.CITY,''))) + ', ' END)
			+ (LTRIM(COALESCE(MA.[STATE],'') + ' ') 
			+ REPLACE((CASE WHEN LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ','')) > 5 
			THEN LEFT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),5) + '-' + RIGHT(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''),ABS(LEN(REPLACE(COALESCE(MA.POSTALCODE,''),' ',''))-5)) 
			ELSE COALESCE(MA.POSTALCODE,'') END),'--','-')
		  ) AL2
		  , ROW_NUMBER () OVER (
			PARTITION BY C.GLOBALENTITYID
			ORDER BY GEMA.MAIN DESC, MA.MAILINGADDRESSID
		  ) ROWNBR
	FROM CONTACTS C
	INNER JOIN GLOBALENTITYMAILINGADDRESS GEMA ON C.GLOBALENTITYID = GEMA.GLOBALENTITYID
	INNER JOIN MAILINGADDRESS MA ON GEMA.MAILINGADDRESSID = MA.MAILINGADDRESSID
	)
--Main Query
SELECT P.PLPLANID, P.PLANNUMBER --TDC-Online Plan Number
	, P.APPLICATIONDATE
	, OWN.CONTACTNAME, OWN.COMPANYNAME --Owner Company
	, OWN_ADD.AL1 OWNERADDRESS_LINE1, OWN_ADD.AL2 OWNADDRESS_LINE2 --Owner Address 
	, CS.MEMO_ProjectNameTitle --Project Name/Title
	, CS.TXT_PlanNo --TW Plan Number
	, CS.AUTOTXT_Twnshp_Sect_Range TRS
	, (SELECT [IMAGE] FROM RPTIMAGELIB WHERE IMAGENAME = 'TucsonLogo') AS TucsonLogo --Subquery to get the city logo from the report image library
	, (SELECT [IMAGE] FROM RPTIMAGELIB WHERE IMAGENAME = 'TucsonWaterLogo') AS TucsonWaterLogo --Subquery to get the department logo
FROM PLPLAN P
	LEFT JOIN CONTACTS OWN ON P.PLPLANID = OWN.PLPLANID
		AND OWN.CONTACTTYPE = 'Owner' AND OWN.ROWNBR = 1
	LEFT JOIN CONADD OWN_ADD ON OWN.GLOBALENTITYID = OWN_ADD.GLOBALENTITYID
		AND OWN_ADD.ROWNBR = 1
	LEFT JOIN CUSTOMSAVERPLANMANAGEMENT CS ON P.PLPLANID = CS.ID
--WHERE P.PLPLANID = @PLPLANID
--WHERE OWN_ADD.AL1 IS NOT NULL


--(1) ProjectNameTitle, PlanNo, TRS
--WHERE P.PLANNUMBER = 'TW-WCP-0123-00048'
--WHERE P.PLPLANID = '00132de2-e999-4470-9d69-62c7fd0408df'

--(2) Contact Info 
--WHERE P.PLANNUMBER = 'SD-1122-00003'
--WHERE P.PLPLANID = 'ad546dfc-265f-48fe-9529-9eb9992c20ef'

--(3) 
--WHERE P.PLANNUMBER = 'TW-WCP-0923-00111'
--WHERE P.PLPLANID = '02cfca1e-76f7-4a00-a50b-b94053e701f4'

--(4) 
--WHERE P.PLANNUMBER = 'TW-WCP-0423-00072'
--WHERE P.PLPLANID = '04e182f6-21b1-4b76-b012-3ca9ff58015b'



--END
--GO


